import { useState, useRef, useEffect } from 'react';
import Head from 'next/head';

const LOGO = '/9j/4AAQSkZJRgABAQAAAQABAAD/4gHYSUNDX1BST0ZJTEUAAQEAAAHIAAAAAAQwAABtbnRyUkdCIFhZWiAH4AABAAEAAAAAAABhY3NwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAA9tYAAQAAAADTLQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAlkZXNjAAAA8AAAACRyWFlaAAABFAAAABRnWFlaAAABKAAAABRiWFlaAAABPAAAABR3dHB0AAABUAAAABRyVFJDAAABZAAAAChnVFJDAAABZAAAAChiVFJDAAABZAAAAChjcHJ0AAABjAAAADxtbHVjAAAAAAAAAAEAAAAMZW5VUwAAAAgAAAAcAHMAUgBHAEJYWVogAAAAAAAAb6IAADj1AAADkFhZWiAAAAAAAABimQAAt4UAABjaWFlaIAAAAAAAACSgAAAPhAAAts9YWVogAAAAAAAA9tYAAQAAAADTLXBhcmEAAAAAAAQAAAACZmYAAPKnAAANWQAAE9AAAApbAAAAAAAAAABtbHVjAAAAAAAAAAEAAAAMZW5VUwAAACAAAAAcAEcAbwBvAGcAbABlACAASQBuAGMALgAgADIAMAAxADb/2wBDAAUDBAQEAwUEBAQFBQUGBwwIBwcHBw8LCwkMEQ8SEhEPERETFhwXExQaFRERGCEYGh0dHx8fExciJCIeJBweHx7/2wBDAQUFBQcGBw4ICA4eFBEUHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh4eHh7/wAARCAIpAh0DASIAAhEBAxEB/8QAHQABAAIBBQEAAAAAAAAAAAAAAAcIBgECAwQJBf/EAFcQAAEDAgMEBAgHCwkGBQUAAAABAgMEBQYHEQgSITFBUWFxEyI3coGRsbMUMjN0daGyFRgjNDU2QlJWYnMWgpKUlbTB0tMkQ3aiwtEXJVNUVWWDk+Hw/8QAHAEBAAIDAQEBAAAAAAAAAAAAAAMEAgUGAQcI/8QAOREBAAIBAgQBCAkEAgMBAAAAAAECAwQRBRIhMRMGMjNBUXGBsSI0UmGRocHR8BQVNXJC4SNigvH/2gAMAwEAAhEDEQA/ALlgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcdTNFTU8lRO9GRRNV73LyRETVVDyZiI3lpWVVNR0z6mrnjghYmrpJHI1qelTCbhmzgqkmWJLhLUKi6KsMLnN9fJSE8y8bV+LbvJpK+O2xOVKeBF0TT9ZydLl+oxA2+Hh0cu+Ser5xxPy3yVyzTR1jlj1z6/dHRaqw5i4QvU7aeku0cczuDWTtWNVXqTXgplhSknDIPHFTVzfyXu07pXIxXUUr11donNir08OKdyp1EWp0Hh15qSvcC8r51maNPqqxEz2mO2/smEzAA1rugGkj2RsdJI5rGNTVznLoiJ1qRRjvOOht75KLDcTK+obwdUv+Rav7vS7v4J3kmLDfLO1YUdfxLTcPx+JqLbfOfdCVpZI4o1kle1jE4q5y6IhjN1zBwfbXKyovtK56c2wqsi/8upWvEOJr/iCZZLrc5506Gb2jE7mpwQ+QjDZY+Gx/zn8HDavy6vM7abF09tv2j91j585MGRrpHLWzdradU9uhw/8AjThLoiuK/wD2U/7leEYbkYTf2/D97Wz5Z8Tn7P4f9rERZy4Qeujkr4061g19in0KbNXBM2n/AJo+PX9eB6f4FaUYbkYYzw/F96SnlnxGO8Vn4T+61VJjjCVVokWIKHVeSOk3V+syFFRURUXVF5FOYGfhmechcGk/FYfMb7CjqtPXDttPd1/k7xvLxTxPFrEcu3b79/2coAKbpgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw7OiqlpMtbtJC5WuexkaqnU57Wr9SqZiYPnr5Mbn50PvWkuDrlr74a7i9proM8x9m3ylWEAHTPgwc9ruk9nudNcqR+5PTSJIxe1FOrI7dafGutajGqiKY3mIjqsael5vE17wu9hO90uIsO0d5o3IsVTGjtNfiu5Oavai6od6uqqeipJaurlZDBE1XPe5dEaiFadk/HqQX6pwZXzaQ1us1Crl4JKieMz+c1Ne9q9ZkWeWM33O5yYct8qpRUj9KhzV+VlTmnc3l369SGhjSzbLyR2/R9eycfpg4bGpv1v229tv29fufJzSzErcTzvt1ue+mtDV03UXR0+nS7s6k9fZH6MOZGG5GG6x0rjry1fK9Zqs2tzTmzTvM/zaPucSMNyMOVGm5GmW6CMbiRhuRhyI03I083ZxRxI03I05Eaaoh5uzijSBv4ZnnIW8pPxWLzE9hUiFPwzPOQtvS/isXmJ7DW8Qnzfi73yKrt43/z+rkABrHeAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABg+evkxufnQ+9aZwYPnr5Mbn50PvWk2n9LX3w1vGf8fn/wBLfKVYQDR3I6V8IdK4TbjFMQu1SrnqmpkN7k0Yph1Y7ekUq5rN/wAMwxtu7+E1qkxJRVFHM+CanlbO2Vi6KxWrqip6UQk5iOVNXKrnLxcqrqqqvMwXL6BFlqKhU/VYi/Wv+BIKIe4o2rv7WGvyTkzTT1V/Vxo01RpyaGuhnurRRsRpqiG7Q10PN2cUbdDXQ3A83ZxRpoNDUHm7OKN0PyzPOQtrS/i0XmJ7CpUPyzPOQtrS/i0XmJ7DXa+fNdv5H128X/5/VyAA1ztgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwfPXyY3PzofetM4MHz18mNz86H3rSbT+lr74a3jP+Pz/AOlvlKsJo74pqaLyOlfCHwL6i7qmH1Pyimb3mLejXgYbXMVsilPNHV0nDLxy7MpwC5Et83Wk2v1IZ4nFNSNMC1SR1k1K5dPCtRze9P8A9L9RItDJvwInS3gpnWd6RKtmry6u9Z9fVz6ADU83ZxQBpqaanm7OKNxpqbdTRVG7OKN6qaKpsVxorjzdlFHNCv4ZnnJ7S29L+LReYnsKhwu/DM85PaW8pfxaLzE9hr9d/wAXZeSkbeL8P1cgAKDsQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAwfPXyY3PzofetM4MHz18mNz86H3rSbT+lr74a3jP+Pz/wClvlKsIAOlfB3VrYt9ioYheKVWvVUQzd7d5D5Nzo0kaqohFkpvDYaHUeHbaWEQSyUtUyeJd18btUUkuw3OKqp2VMS+K5NHt/VXqMBuFG5jl4GlluU1qqt5EV0TuEjOtOvvK9Lck7T2bnVYf6mkZMfnR2/ZLaORU1TiihVPj2q4wzwNlhkSSJ3Vzap9FJEcmqLqhlaJhBgyVyxt2mO8OZXG1XHErjar+0w3Woo5VcaK/tOFXmx0g3ZRVzq42q/tOushsdIebsoq7cUn4ZnnJ7S4lL+KxeYnsKYQy/h4/OT2lzqT8Uh8xvsKOs9TrfJeNvF+H6uUAFF1oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYPnr5Mbn50PvWmcGD56+TG5+dD71pNp/S198Nbxn/H5/wDS3ylWEAHSvg4bJGI5DeA97PkV9C2RF4GOV1uc1VVGmcOaiodWopWvReBFfHEthptbbH0lhFDVVlsn8JA7RF+M1eTjMLNfqasRGI7wM/TG5efd1nQrLWi6qiHyKm2OauqIpFHNTp6mwtbDqfpb7W9sM+8Nrz4GjpO06eUcNNdcVQYdv1dPTw1rVipahNF8FN+gjtebV+LpqnFU48yScTZQ4qtW/JSQx3SnTVUdTr4+naxeOvdqR2tj3232n71vFg1sY/E5Oeseuvf4x3/RHzpTY6XtOW4W+so5nQ1UE1PK1dFZKxWqnrOhK2VnFWqqdaHs0tBj1WG88u+0+yejmdL2nG6XtOo+bQ4nTdpHutxV9CKX8PHx/ST2l3KP8Th/ht9hRGKf8PHx/ST2l7aH8Sg/ht9hS1nqdV5NRt4nw/VzAApOpAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADB89fJjc/Oh960zgwfPXyY3PzofetJtP6WvvhreM/4/P/pb5SrCADpXwcAAAAAbXMRTglpmO5oh2QNmUWmOz5q0SxytliVWSMcjmuauioqclQuBldiVuKcHUdwe5FqmN8FVJ1SNTivp4L6SqCohImQ+JvuFipLdUSbtHctI115Nk/RX/D0lHW6fnx7x3h1XktxidJrIx5J+hfpP3T6p/ntWIudst1zhWG40NPVRr+jLGjvaR/iTJrDdwR0lskmtcy8kYu/H/RXj6lJLBpsea+PzZ2fUNZw3Sa2Ns+OLfP8AHuq7jDKTEtpa+VKJtypk4+FpNXORO1vxvVqhGddap41d4FVVUXRWO4Khe4xnF2BcN4nY51woWsqVThVQaMlTvX9L06l2mui3TJHxhy2q8k74vpaHJt/626x8J9X86qQeEfFVsZI1zHI9OCpp0l/6D8Rp/wCE32IVozHykudjhkrmNZc7bF46zMTdkiROlydHeiqncShlxmrabzHBbLsjLdXI1GMcrvwUuidCryXsX1jU4/ErF8fWDgWujR57abWx4d52237T37T2SaAioqapxQGuduAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGD56+TG5+dD71pnBg+evkxufnQ+9aTaf0tffDW8Z/x+f8A0t8pVhAB0r4OAAAAAAAAGrXK1yOaqoqLqip0GgD1aXKLFTcU4Tilmei19JpDVJ0qqJwf3OTj369RmJVXKnFTsKYriqpHL8BqPwNW391V4O062rx9adJaiKRksTJYntex6I5rmrqiovJUOf1mDwsnTtL7N5M8W/uOjiLz9OnSf0n4/PduABUdGxzM/jl1iFP/AKdN9hSmNJXS0yo1+r4/rTuLZ59XyKz5c18KyNSouDfgsLV5rvfGX0N149xUiWM22giYpMvnHljkx31VMc9do6/GU15UZr1Fp8DbrzM+stS+KyVeMkH/AHb2c06OosLR1NPWUsVVSzMmglajo5GLqjkXpQoZTTyUku+zi1fjN6FJhyYzHdh+pjoa6V0lmndoqLxWncv6SdnWnp7/AHU6SMkc9O/sY8B8or6O1dPqrb456Rae9fun7vl7llwbYZI5omSxPa+N7Uc1zV1RUXkqG41D6TE7gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAYPnr5Mbn50PvWmcGD56+TG5+dD71pNp/S198Nbxn/H5/8AS3ylWEAHSvg4AAAAAAAAAANFQlrKjNVlmpIrJiLwj6ONN2CpaiudEn6rk5qnVpxQiY0VCPLhrlry2X+HcS1HDs3jYJ2n8pj2St9QYrwzXQpLS3+2yNVNfxlqKneirqnpPj4nzLwjYqdznXSGunRPFgo3JK5V6lVODfSpVhTaqalGOG0ies9HV5PLrVWptXHET7es/k+1mJi65YyvS19dpHDGitp6dq6tib/iq9K9P1GJyMO89pwvaXYpFY2hymTU5M+ScmSd7T3l86WMUNQ6kn1X5N3Byf4nZkYdaWM8mNuqWtotHLKyGz1jJaiFcLV828+NqvoXuXm3mrPRzTs16kJlKT4Nu1Ta7hTVtM9Wz0crXsXrRF5f4FzbNXQ3S00txgXWKpibK3uVNTU6/DFbReO0vo3khxK2fBbS5J3tj7ffX1fh2/B2wAUHYAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGEZ6JrljdO+L3rTNzCM8/JjdO+L3rSbT+lr74a3jH+Pz/wClvlKsAAOlfBwAAAAAAAAAAAABoqGim40VANipqcb2nMptVNTxnEuq9p15GHee04XtMZhPS7ht/iVaJ+sioWsyDr/huXVNE5VV1LLJCuvfvJ9TkKrQt3ahi9pYzZlqFdh660uvCOrST+kxE/6Slrq74fdLqfJLNy8UiPtVmP1/RLYANI+rgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGEZ6eTG6d8XvWmbmEZ6eTG6d8PvWkun9LX3w1vGP8fn/0t8pVgAB0z4OAAAAAAAAAAAAAAAA0VDRTcaKgGxU1ON7TmU2qmp4ziXXa38I3vJ82YUX4JfF6PCQ+xxBLW+OhYTZnp0Zha5VWnGWs3PQ1jf8AupT13TBLpvJOJvxXHPsiflKWAAaF9hAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMXzXolr8vLzAnNtOsqdu4qO/wADKDiq4GVNLLTyIislYrHIvSipoZUty2i3sQarDGfBfFP/ACiY/GFLgdy90MlsvFZbpU0fTTOjX0LodM6mJ3jeH5+vSaWmtu8AADEAAAAAAAAAAAAAAABoqGim40VANGpxLQ5HW/4Blzb1czdfUq+d3bvOXRfUiFaLVRy3C401DA1XS1ErY2J2quhcW00cdvtdLQxJpHTxNjanYiaGs4lfasVd55C6WbajJqJ7RG3xn/8AHZABp304AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV32h7EtvxbHdomaQXGPVypy8I3g76tFIxLW5pYaTFGEKmhjai1cX4amX99qcvSmqekqm9rmPcx7Va5q6KipoqKb7Q5vEx7euHx7yt4bOj105Ij6OTrHv9cfj1+LQAF1ywAAAAAAAAAAAAAAAAAb4IpJ52QQsdJLI5GsY1NVcqroiIHsRv0hJWz1h9blit93mZrT25u81VTgsruDfUmq+osSY3lthtmFsJ0ttVGrUqnhalyfpSO5+hOCegyQ53VZvFyTMdn23ye4b/btDXHaPpT1n3z6vh2AAVm8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgHP3Bbrfc3Ymt0C/A6p3+1NanCOVf0u53t160J+OvcqKmuNBNQ1kTZqeZiskY7kqKT6fPOG/NDU8Z4Vj4npZw26T3ifZP87qYgzDM7BFZhC7KiI+a2zuVaafT/AJHfvJ9Zh50VL1vXmr2fE9Vpculy2w5Y2tAADJXAAAAAAAAAAAAAAmDZ9wYtTV/yquMX4GBVbRMcnxn9L+5OSdvcYjlbgirxfdkc9rorZTuRambTn+43tX6k9GtnqGlp6KjipKWJsUELEZGxqaI1E5Ia3Xanljw6957u58keAznyRrM0fRr5v3z7fdHzcwANM+ogAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA6d7tdBebZNbrlTMqKaZNHMd7UXoVOtCuGZWXFzwrO+rpUfW2lV8WZE1dGnU9E9vJezkWbNssbJY3Rysa9jk0c1yaoqFnT6m+GenZpOM8C0/FafT6Xjtb9/bClYJ9x7k5Q3B0ldhuRlDUrxWmf8i9exebfrTuIVxDYLxYKtaW72+alf+irk8V/a1ycF9Bu8Opx5o+jPV8o4nwPWcNt/5a/R+1Hb/r4vmAAnacAAAAAAD6eHsP3nEFX8GtFvmqn/AKStTRrPOcvBPSeTMRG8pMeO+W0UpG8z6ofMM5y3y5umK6iOpqGvo7Si+POqaOkTqYi817eSdvIkXAeTlDbnR1uJJGV9SnFKZmvgWL2rzd9Sd5K0UccUbYomNYxqaNa1NEROpDWajiER9HH+LvOC+Rt7zGXXdI+z659/s93f3OrZLXQWW2Q2220zKemhTRrG/Wqr0qvSqncANTMzM7y+kUpWlYrWNogAB4yAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA4K+io6+ldS11LDUwP8AjRysRzV9CnOB2eWrFo2nsjjEGTmFbi50lD8Itcq68IXb0evmu9iKhhF1yPvsL3LbrpRVTETh4RHRuX0cU+sn4FqmszU9bQaryX4ZqZ3nHyz/AOvT8u35Kv1WVeOIFX/yjwqJ0xzMd/idJcvMaoun8nqz+in/AHLWgnjiWT1xDVW8hdDM/RvaPw/ZVymyvxvOvCyvj/iSsb7VMgtOSWIp3NW4V1DRsX4yIqyOT0Jw+ssGDG3Ecs9toTYfInh1J3vNre+f2iEbYcybwxblZLcX1F0mbzSRdyPXzU4+tVJCoKKjt9K2loaWGlgZ8WOJiNanoQ5wVMmW+Tzp3dFo+HaXRRtgxxX5/j3AARroAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAfMxZeIsP4Yud8nYskVBSyVDmpzcjWqun1H0zD87PJDiz6JqPsKe1jeWGW01pMx7FM8S5zZiXq+PuaYkraBN/WKnpJFjijTXVE3U+N/O1LC7NmdMuM3/yYxO+NL2xiup6hERqVTUTiipyR6c+HBU16inB27Lcq2z3alutundBV0srZYZG82uRdUL98VbRs5HT6/Liyc8zMx63pmDEMosb0WPsE0l9pt1lQqeDq4UX5KZE8ZO7pTsVDLyhMTE7S6+l63rFq9pAAeMkFbWmY9+wZbLVacOzrR1Nz8I+WqaiK9jGbqbrdeSqrufRpwITyezjxtasb22C43ysutvrKqOCogq5Vk4Pcjd5qrxRU114Gb7dX5Ywv83qPtMICwV+eVk+kIPeNLuKlZx9nL67UZa6ydrT02ek6cgaN+KncalJ1AAAAAAAAAAAANHKjWq5yoiImqqpXTFm1LbbdiGahsuGH3OhgkVjqqSs8Csui6KrW7jtE6lVePUhlWlrdkGfU4sEROSdt1jAY9l3i+1Y4wpS4itCvSCfVr45NN+J6fGY7TpT60VF6TITyY26Ja2i0RavaQAHjIAAAAAAABW/NvaRqLFiaqseFLXS1SUUixTVVUrla56Lo5GtRU4IvDXUzPIHOaDMh9Taq+hZQXmmi8MrI3K6OaPVEVzdeKKiqmqL195X3OnJzGdmxrcau2WWtu1sral88E9JEsqtR7lduvRuqtVNdOPBSStkrK3EdgvlTi7EdFLbWrTOgpaaZu7K5XKiq9zebURE00XiuvZxtWrj5N4aHBn1k6rltHTf2dNllQAVW+AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMPzs8kOLPomo+wpmBh+dnkhxZ9E1H2FMq+dCLN6O3ul54nPLR1cVHDWS00zKadXNhlcxUZIrdN5EXkumqa95wFoMqMA0uYOzA61OaxtwhrqiagmX9CVNOGvU7kvfr0GwvfkjeXHabTzntNa99t0WbOuYz8v8bMWskX7i3BWw1zehnHxZU7WqvHsVewvfFIyWJksT2vje1HNc1dUci8lRTzKuNHVW6vnoK2F8FTTyOjljemitci6KilstkHMr7r2b+Q14qEWut7NaB73cZYE/Q72dH7vmkGox7xzQ2nCNXy28C/w/ZYUAFR0Squ3V+WML/N6j7TCAsFfnlZPpCD3jSfdur8sYX+b1H2mEBYK/PKyfSEHvGl/F6NyOv8ArlvfHyh6TN+Kncamjfip3GpQdcAq3nFtF4jtONa+xYUpaGGlt07qeSepiWR80jV0domqI1uqKic1XTXXjoSrs85ny5lYcqpa+kipbpQSNjqGw6+Dejk1a9qKqqnJeGq8iScVorzSp49dhyZZxVnqk8AEa4A2TyMhhfM9dGMarnL2ImpUPFW09jB+IZnYforXTWuKRUhjqIXSPkai83rvJz6k00M6Y5v2VdTq8emiJv61vwYfk7jeHMHAtLiFlN8Fmc50NTCjtUZK3novUqKip3n18b4jt+EcKXDEd03/AILQxb72sTVz1VUa1qdquVE9JjNZ32TVy1tTxInp3d+8fkis/gP+yp5nVH4xJ56+0sNddqi91LamGmwnb4qeVrmNSSpe56IqacVRERV9BXeR2+9z14byqpcwUtTfdzfFNVi1E18Od9t1ytijyS1v0xN7qInMozlFndd8ucMS2KhslDXRS1TqlZJpHtciua1unDo8VPWZj99biT9lbT/+aQjyYbzaZhe0nEtPjw1paesR7FtQVty72nH3jE9HaMQ4ego4KyVsLKmmmcvg3OXRN5rk4pqqcUXh2lkiC1Jp3bPBqceojfHO4DEM4MbRZf4Gq8RPpkqpWObFTwquiPkdy1Xq5qvcVuwxtP4wjxDC+/0FsqrXJIiTRU8KxyRtVebHK5dVTqdrr1pzMq4rWjeEWfXYcF4peesrgAiLOfPKx4Fp4qO2RMu95qIWyxwo/SOFjk1a6RU48U4o1OKp1cCut12hs1K2pdLDfYKCNV1SGmoot1vpe1zvWp7TDa0bo9RxPBgtyz1n7l5wUYs20JmjQ3KGpqr7HcYGORZKaakha2RvSmrWo5O9FLvWmsZcbVSXCJrmx1UDJmtdzRHNRURfWeXxzTuk0utx6rfk36e12QVpz32gL9hvGlVhnCtLRMSgcjKmpqY1kc+TRFVGpqiIia6cddewzrZwzZqsyLdX0t3o4Ka62/cc91OipHMx2qI5EVVVFRU4prpxTTqROK0V5imuw3y+FE9UuAAjXAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADD87PJDiz6JqPsKZgYfnZ5IcWfRNR9hTKvnQizejt7peeJdrY68jEHz+f2oUlLtbHXkYg+fz+1C5qPMc3wb6x8JYFtiZa7qpmBZ6fxVVsd0YxOS8my6epq+jtK54avNfh6/Ud6tcyw1dJKkkbk606F7F5Kh6S3KipLlb6i310DKilqY3RTRPTVr2OTRUX0FAM68A1WXuN6m0PR8lBLrNQTu/3kKrwRV/WbyXu15KhjgvzRyyl4rpJxX8anafyleDLDGNBjrBtFiCgc1Flbu1ESLqsMqfGYv+HWiovSZOUa2ZsyVwLjJtFcZ1bYro5sVVvLwhfyZL2acl7F16ELyNVHNRzVRUVNUVOkr5aclm30GqjU4t57x3VW26vyxhf5vUfaYQFgr88rJ9IQe8aT7t1fljC/zeo+0wgLBX55WT6Qg940t4vRue1/1y3vj5Q9Jm/FTuNTRvxU7jUoOuec2avlNxR9L1XvXE+7CnyGKfOp/Y8gLNXym4o+l6r3rifdhT5DFPnU/seXsvo3KaD67Hvn9VnAAUXVurefyRWfN3/ZU8zJPlHd6npnefyRWfN3/ZU8zJPlHd6lvTetz/ABzvT4/ouhsXeSCb6Vm+xGSjj7DNFjHCFxw3cHvZT10W4r2fGY5FRzXJ3ORF9BF2xd5IJvpWb7EZNpBkna8tpo6xbS1ie0wqBddlvFNKlRLT4htM1PE1z2ue17HORE15aLovpIBe1WPc1eaLoemd4/JFZ/Af9lTzOqPxiTz19pawZLX33aLimkxaea+HHfdJ2VOSmIMxMNy3y13K3U0EdS6mVlQrt5XNa12vBF4eMhlv3rGMv/nbL65P8pJuxP5Jq36Ym91ETmRZM162mIXtLwzBkw1vaOsx7VY8u9mS4WzE9FdMSXyjlpqOZkyQUrHKsrmrqiKrtNE1ROhSzgBDe837tnp9Lj08TGOEK7ZnkeT6Rh9jilZdTbM8jyfSMPscUrRFVUROalvT+Y53jH1j4Qz3LDLfFWZ93kWicraaJWpVXCqcqtZw4J1udonJPqJ4oNlTDjKZqV2JrpLPp4zoo2Mbr2IqKv1kuZPYcpcLZb2W1U0LY3JSslqFROL5XtRz1VeniunciGWkF89pno2ml4XhrSJyRvMoJtGzBgejuMNTVXK610UbkcsEjmNa/ToVUTXTuJ1jY2ONsbGo1jURGoicERDUEVrzbu2GHT48O/hxs8+9oDyz4p+fu9iEqbC/5y4j+ZxfbUivaA8s+Kfn7vYhKmwv+cuI/mcX21Ll/ROa0v1/4z+q2AAKLqwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADD87PJDiz6JqPsKZgYfnZ5IcWfRNR9hTKvnQizejt7peeJdrY68jEHz+f2oUlLtbHXkYg+fz+1C5qPMc3wb6x8JTIR5n5l7DmDgiakiYxLrSazUEqpx39OLNepycO/RegkMFKJmJ3h02THXJSaW7S8xaunmpKqWlqYnxTRPVkjHJorXIuioqFwtknMr+UeHf5I3ao3rra40+DOcvGanTgnereXdp2mFbYWWvwKtTH1np0SmqXJHc2Mb8SReDZe53Je3TrIEwfiC44WxJQ361SrHVUcqPb1OTpavYqaoveXpiMtHLY7X4fqdp7fOE/bdX5Ywv83qPtMICwV+eVk+kIPeNJc2qMWWzGltwVfrXK1zJ6OdZItfGhfvMRzHJ0KioveRHgr88rJ9IQe8ae4o2x7MNbaLaubR2nb5Q9Jm/FTuNTRvxU7jU17r3nNmr5TcUfS9V71xPuwp8hinzqf2PICzV8puKPpeq964n3YU+QxT51P7Hl7L6Nymg+ux75/VZwAFF1bq3n8kVnzd/wBlTzMk+Ud3qemd5/JFZ83f9lTzMk+Ud3qW9N63P8c70+P6LobF3kgm+lZvsRk2kJbF3kgm+lZvsRk2kGXz5bXQ/V6e51bx+SKz+A/7KnmdUfjEnnr7T0xvH5IrP4D/ALKnmdUfjEnnr7SfTetquOd6fH9FyNifyTVv0xN7qInMgzYn8k1b9MTe6iJzIMvny2ug+rU9wACNbQrtmeR5PpGH2OKWxfKs85C6W2Z5Hk+kYfY4pbF8qzzkL2n8xy3GPrHwh6XYf/INv+axfZQ7x0cP/kG3/NYvsod4oy6ivaAAB68+9oDyz4p+fu9iEqbC/wCcuI/mcX21Ir2gPLPin5+72ISpsL/nLiP5nF9tS9f0TlNL9f8AjP6rYAAourAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMPzs8kOLPomo+wpmBh+dnkhxZ9E1H2FMq+dCLN6O3ul54l2tjryMQfP5/ahSUu1sdeRiD5/P7ULmo8xzfBvrHwlMgAKLqXUvVsorzaaq1XKnZUUdXE6KaN3JzVTRTz7zdwPW4AxtV2Kp3pKfXwtHOqfLQqvir3pyXtRT0PIx2i8uo8fYJf8Ejb92bejpqJ3S/h40fc5E9aITYcnJPXs1vEtJ/UY96+dH82UPPr4K/PKyfSEHvGnypo5IZXxSscyRjla5rk0VFTmin1cFfnlZPpCD3jS9PZytPOh6TN+Kncamjfip3Gpq3ePPfPa2TWjODFFJMmiuuEk7fMlXwjfqchJmxPiOkt+MLph+qkbG+5wNfT7y6bz49VVqdu65V9CmYbYeW1Td6SHHVmp3S1FFD4G4RMTVzoUXVsiJ07uqovZp1FU6GrqaCthraKeSnqYHpJFLG7dcxyLqioqclL9dsmPZyeWLaLV823Tff4S9OAVZwBtSS09DHSYzs0tXKxunw2hVqOk7XRromvWqL6EMnue1Pg6Kle632O81NRp4jJEZG1V7XbyqnqUqzhvE7bN9XiWmtXfm2Srm3iSlwpl5eLxVStYrKZ7IWqvx5XJoxqd6qeda8V1JEzIzCxhm3foKV1O9YGOctHbKRFc1vBdXL0udprq5eSa6InEjteC6FrDj5I692g4jq41N4mvmwujsXeSCb6Vm+xGTaQlsXeSCb6Vm+xGTaVMvny6LQ/V6e5w10Sz0U8Kc5I3NT0poeaF1p5KS51VLM1WyQzPY5F6FRVRT01Ka7WGWtXh/Fc+LrdTufZ7pJvzKxvCnnX4yO6kcvFF61VO+TT2iJ2UeM4bXxxePUkjYgutJLgS72ZsifC6a4LUOZ07j2NRF9bFLBHm5grFV9wdfI7zh+ufSVTE3V0TVsjV5tc1eCoTJBtUYybEjZrDZJHpzc1JGovo3lMsuC023hFouKYseKKZOkwt+Cose1VipHtWTDdoczXiiPkRVTv1LHZT42oswMGU2IqOB1Mr3Oingc7eWKRvNuvSnJUXqVCG+K1I3ls9PrsOoty0nqwHbM8jyfSMPscUti+VZ5yF0tszyPJ9Iw+xxS2L5VnnIWtP5jQ8Y+sfCHpdh/8AINv+axfZQ7x0cP8A5Bt/zWL7KHeKMuor2gAAevPvaA8s+Kfn7vYhKmwv+cuI/mcX21Ir2gPLPin5+72ISpsL/nLiP5nF9tS9f0TlNL9f+M/qtgACi6sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA+fiW001+w9cLJVq5Keup308it5o1zVRVT1n0AHkxExtKl9y2Zswob26kon2ypoVfoysdUbiI3Xgrm6byL2IilpcpsGwYCwLQYbiqFqXw7z55tNPCSOXVyonQnQnYiGVgkvlteNpVNPoMOntNqd5AARrgAAK9Z9bP0mJrvLiXBslLTV8671XRzLuMmd0va7kjl6UXgvPVOnHsmNnW/0GKqO+4yfS01PQypNFSQy+EfK9q6t3lTgjUXReaqunQWmBLGa3LsoW4bgtl8Tbr+QACJfaOa1zVa5Ec1U0VF5KV9zZ2bLZfKqW64NqobRVyKrn0crV+DvXraqcWd2ip2IWDBlW81neEOfT489eW8bqG3XIfNO3zKxcLyVTddEkpqiKRru3Te1T0oh9DDWzvmZdqhrau2U9ngXnLWVLOCeaxXO170QvECb+os10cGwRO+8/wA+CM8oMm8OZfUckjVW5XaeNY562ViJo1ebWN47qelVXrIWxTsu4mdiKodh67Wl1rllV0XwqR7JImquu6qI1UXTlqi8ewtqCOMtondaycPwZKRSY6QxLKPBNNl/gilw7BULVSMc6WonVu74SV3NUToTgiJ2IhloBhMzM7yt0pWlYrXtAcFwo6S4UU1FXU0VTTTNVkkUrEc16L0KinODxlMbq/Y32X8N3OpfVYZu9RZXPVVWnkj8PCnY3ijk9amDSbKuK0eqR4kszm68FVsiKvo0LdAljNePWoX4Zprzvy7Kis2VcVq9EfiSzNbrxVGyKqJ3aFj8qME0WX+DKbDtHO6pWNzpJ53N3Vlkdzdp0JyRE6kQysHl8trxtKTT6HDp7c1I6sTzZwVTY/wTV4dqKhaZ0itkgnRu94ORvJVTpTmi95XTDWy3if7vw/d+82qK1xyIsrqR73yyNTjo1HMREVeWqrw6lLbgVyWrG0GfRYc94veOsNsMbIYWQxtRrGNRrUToROCG4AjWwAAVxzy2fLtirGNTiXC1xoY3Vqo+qp6xzmaP0RFc1zWu116l0M32d8ppMtLdXT3KuhrLrcN1JVgRfBRMbro1qqiKuqrqqqidHDhqsrgknLaa8qpTQ4aZfFiOoACNbAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAARTnTnXYcvt6207Eul8VuqUrH6Nh15LI7o7k49xV7FGb+ZeMK7wKXqtp2yO0jpLYjok48NE3PGd6VUlphtbq1+p4lhwTy95+5fRZYk5ysTvchq2Rjviva7uU894cu8y7prN/Ja/zKvFXTQvRV/paG2TDmZmFHLWJasS2rwScZ4WSsRqec3hoSeBH2lX+7XjrOKdv59z0MBSLAW0NjzDs0cN1qG36hbojo6pNJUTskTjr52pavK7MjDWYVrWqstSrKmNP9oo5dEliXtTpTtTgRXxWp3XdNr8Oo6VnafZLMgARroAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAGB5744TAOXlZeId1a+ZUpqFruSyuRdF/moiu9GhnhV3brrJfDYVt6KqRbtTM5NeCu/Bonq4+skxV5rRCprs04cFr17ogypwPes1sdSU8lVKkauWouVfJ4ysaq8V483uXknevJFLtYDwDhXBNubR4ftUMDt1EkqHojppV63PXivdyToRCK9iW3U0GXNxuLGt+EVVwcx7tOO6xrd1PrVfST2Z5rzNtvUq8L0tKYoyTG9pAqIqaKiKnUoBA2qL82slMKY6opp4KWG03vRXR11PGib7uqRqcHovXz7ehaf082Ksqcw103qG72ybdkZrqyVvPRf1mOT6lPRAiHaGydTMeKkuNqqYKO80jVj35UXcmjVdd1ypxRUXVUXtUnxZdvo27NTr9Bzx4uGNrR7PX/wBs+y8xTQ4zwdb8R0Hix1cero15xvTg9i9yoqGQGB5FYEqMvMCMsVXWsrKp876iZ0aLuNc7RN1uvHTRE9OpnhDbbfo2OGbzjrN++3UAB4lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMDzPzYwll5VUtJfZKuSqqm77IaWJHuazXTedqqIia9uvBTPCnO215T7d9FM95ISYqRe20qWv1FsGGb07rbYcvNuxDY6O9WmoSooqyJJIZETTVF606FTkqdCn0CN9mTyH4c/hSe9eSQYWjaZhZw3m+Otp9cQAA8SAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABXjbew9UV2E7NiKCNz2W2ofDPut13WSo3Ryr0IjmIne5Cw50r5a6C92iqtNzp2VFHVRrHNG7k5q/wD9zMqW5bRKDU4fHxWx+1VjY4zBt9lrqzBt3qGU0dwlSailkXRqzaI1Y1XoVURNO1FTmqFtCjedeSl/wJWzXG2wzXLD+9vMqY27z4E6pETlp+ty7uR3MtNobF+FYIrfdmtv1vjRGtSoeqTMb1JJ0/zkUsXx8/0qNPpNdOl/8GojbbtK7AIlwXtB5d4h3IauvlslU7RPB1zdGa9kiat07V0JSt9dRXGlZV2+sp6unemrZYJEex3cqcCvNZr3brHnx5Y3pbd2AAYpQAADEsxsxcK4CoUqMQXBGSvTWGliTfml7m9Xauidp1M7Mf0uXeCZru9rJq6Z3gKGBy/KSqnNf3WpxX1dKFOcGYZxfnLjud8lU+eaR3ha6vn4sgZr1fU1qfUiE2PHzRzW7NdrNdOK0YsUb3lJ+J9qu8yTuZhrDNDTQoujZK97pXuTr3WK1Gr2aqY9DtPZjsl3309hlb+o6keifVIi/WWAwPkTl9hmlj8LaI7vWInj1FcnhNV7GfFRPQZdPgXBU8Kwy4TsjmKmmnwGNP8AAy58UdIqgjS66/W2XaUH4I2p7fUzx02LrA6hRyoi1dE9ZGJ2rGvjIncrl7CwWH71asQWqG6WavgrqOZurJYnaovYvUvYvFCFM09m/Dl3opa3ByJZ7k1Fc2BXK6nlXq0Xixe1OHYQLlfjnEeUWOZaStiqGUrJ/A3O3PXmiLorkTlvJzRU59ynvh0yRvTuxjV6jS3iup61n1r6g61pr6S62yludBM2ekqomzQyN5PY5NUX1KdkrN1E79YDD8yMycJ4Ao0mv1w0qHprFRwJvzy9zehO1VRO06OeeYVPl3guS5IjJblUr4Ghhcvxn6cXKn6rU4r6E6SoOBMJYtzkxxUSPqpJXud4W4XGfVWwtXknavQ1qdXQiE2PHzRzW7NbrNdOK0YsUb3lJmJtqu+SzubhvDVvpYUXRr6575nqnXoxWoi9mqnwKfaezGjm35KWwTN14sdSPRPqkRSwWCcjMvMM00aOs0d2q0Tx6mvTwiuXsb8VPUZVVYDwTUwLBNhOyOjVNNEoo0+tEMufFHSKoY0uuv1tl2lDWAtqGyXGojo8XWh9oe5dPhdO9ZYdetzdN5qd28WAt1dR3KhirqCqhqqWZqPjliejmvRelFTmV6zj2cbVUW6e7YDjdR1sTVetvV6ujmROhirxa7qTl3EXbO+aVfgDFDLHeZZfuDVTeCqIpFX/AGSRV08IiLy0X4ydXagnHW8b0eU1mbTZIx6ntPaV3gq6JqvQEVFRFRUVF5KhpJ8m7uUrtygu1bRtprszG4TTD87KKWt+BRV/whFc5+9uo5Y93g1V/e109RnOa2a2Fcu6drbtO+puErd6Ggp9HSuT9Z2vBre1e3TXQo3Lc5rLmBJd6djHzUV0dUMa/wCKrmS7yIvZwJeylylvebdzqMdY1r6iG3Vc7no5PlatUXRd3Xg1iaaa9mici3bFSvWezn8HENRl3x1je0z+EPoXPatv76hy2zClsgh14JUTvld627qfUc2GdqLElXf6GkuWG7W6knnZHJ8F8IkqI5dNW6uVFXjy04k3WrJvLS207YYsJUEuiaK+dFkcverlPq23LnAltroq6hwpaYKmFyPjkbTpqxyclTtI5vi+ytV02u3iZy/z8GUm2V7Io3SSPaxjU1c5y6IidZuKi7VObVVdr1U4Iw/VOitlG9Yq6WN2i1Mqc2a/qNXhp0qi9GhHSk3naF3Vaqumx89kk5jbSWE8PVEtBh+lkxDWRqrXSRyeDp2r5+iq70JovWRNcdqHMCeVVpLfYaSPXxWpTyPdp2qr+PqQ+1kbs7tvNvp8Q43dNDSzNSSnt8a7r3tXk6R3NEXqTj2lhrTlxgO107YKPCVnaxqaavpWyOXvVyKqk0zip023a6lNdqY55tywrTZNqfGVPM37rWOy18KfGSJJIJF/nbzk/wCUnDK7PDBuOpo6Bkslpur+VJVqieEX9x6cHd3Bew+xiXKXLy/0zoa3C1vicqcJaWNIXt7UVmn1lWc9cl7nl1I292iomrrE6RESbTSWldrwR+nR1OTp4Lpw1R4eTpHSXl51ukjntPPVd4EDbKua9RiyhfhTEFR4S70UW/TzvXxqmJOC69bm8O9F16FUnkgtWaztLa4M9c9IvVEuK9oPL/Dt/q7LUPuVVUUkixTOp6dFYj0XRW6uVNdF6uBWnaOx3ZcwcaUl4sbKtlPFRNgclRGjHbyPcvJFXhxQsJi3ZuwfiDEVbevundKJ9ZK6aSKJWKxHuXVVTVNUTXoK6bQOX9uy6xfS2a2VlVVwzUbahXz7u8iq5yacETh4pZw+Hv07tHxGdX4c+JEcu6Wcms+cFYRy2tGHrpDdnVlGx7ZFhp2uZqr3OTRVcnQqGX/fO5df+3vn9Vb/AJzAso9n3DeMcvLViSuvNzp6isY9z44kZut0e5vDVNegyv71bCP7Q3n1R/5TG3hbzumwzxDw68sRttGzJMNbQ+Xt9vlJaIn3Olmq5GxRPqKZEZvuXREVUcumq9PIl0g/DOzVg6y36jur7pdK1aSZszIZVYjHOauqa6JqqapyJwIb8m/0Wy0s6iaz4+2/3CqiIqquiJzUhbM7aIwnhSqlttogfiC4xruvSGRGQRr1LJouq9jUXvQ+PthZiVeH7PSYQtFQ6CsukSy1cjF0cyn1VqNTq3lRydzV6yNdnbJBuN6X+UuJJZoLKkitghjXdfUqi8V16G68OHFePIkpjrFea6pqtZltl8DTx19c+xuuW1Fj+eVVo7bYaOPXxW+Ake70qr9F9SHZse1NjKnnb917HZq+BF8ZIUkgkX+dvOT/AJSylny2wFaaZtPRYStDWNTTWSmbI5e9ztVU62I8qMvb9SugrcLW6NVThJTRJC9vais0PfEx/ZYf0mtjrGXq+TlXnTg/H0jKGnlktl2VNfgVUqIr+vccnB/1Lw5EllGs9cp7llfdqe62urnqLPNL/s1UnCSnkTijHKnTw1RU56FjNmbMmXHuEJKa5v3rza92Opd/6rFRdyTvXRUXtTtMcmOIjmr2S6TWXtknBnja3zSyACFswAAAAAAAAAAAAAAAAAAAAAAABURyKioiovNFIyx1kZl5it0lRJafuVWv4rU25UiVV61ZorF793XtJNB7Fpr2R5MVMsbXjdULGOy7iih8JNhq7Ud3hTVWwzfgJl7E11avfqhGFZacx8t7j4aSnvlgmR2nhonPYx+n7zfFcnpVD0MOOpggqYXQ1EMc0T00cyRqOaqdqKTRqLevq1mXhGKZ3xzNZU9wPtN4wtTo4MS0dLfaZODpERIKhE72pur6W8essllnmdhPMClV9jrlbVsbrLRVCIyePt010VO1FVDFsx8gMEYpglnt1KliuTkVWzUjdI1X96Pkqd2ilTcT2HFuVeN2QVD5KG40rvC0tVA5dyVuvB7V6UXpRe5UM+XHl83pKCc2r0Mx4v0q/wA/nV6Hgj3IXMSLMTBTK+ZGRXSkckFdE1eG/pqj0T9Vyce/VOgkIrTExO0t3jyVyUi9e0qb7ad9lr8y6WyJIq09rom+J0JJL4zl9LfB+onnZiwvT4byltcrYmpV3RiVtQ9Obt/4ia9SN09KqVk2sPLvfvMpv7vGT3l9nllnacCWG2V1/fFVUlughmZ8DlXde2NEcmqN0XihZvE+HWIaPS5KRrct8kxHqjf3pvBFn3wOVP7Rv/qU3+UffA5U/tG/+pTf5SDw7ext/wCrwfbj8YSmVU23cL09Nc7PiumiRklYjqWqVE+M5iIrHL26KqehCWPvgcqf2jf/AFKb/KRDtS5nYLxvg622/Dd1dWVMFd4WRq08jNG7jk11ciJzVCTFW0XjopcQzYMmntEWiZ96RdjW+z3TKh9uqHq91qrXwR6rqvg3Ij2/W5ydyITYV02GPzTxH8+j92WLMMsbXlZ4fabaakz7FMNs2+zXHNSOzb7vg9qo42NZrw8JIm+53pRWJ/NLEbN+GKbDGU1oZHGiVNfElbUv04uc9NU17m6J6CrO1X5eMQ91N/doi6GXn5hWD6Og92hLl6Y6woaGOfWZbT3j933QAVm7Cumdmz1X4pxs/EOFa230jK5UdWw1KuYjZOl7d1q6681Tr16+FiwZUvNJ3hBqNPj1FeW8OnZKN1ustDb3zuqHUtPHCsrucitajd5e1dNTtyfJu7lNTST5N3cpimiNo2ecX3NdeMxVtLXbq1t2+Do7q35d3X6z0UtFBS2q1UttooWw01LC2GKNvJrWpoifUef+EvLbbP8AiGP+8IehRZ1E9oaTg1Y2vb7wAFZvHwcxbw/D+A75eoVRJqOhlliVeW+jV3fr0KS7POG48YZvWuluDFnponvrKpHcd9GJvaO15ort1F7y3m0H5F8UfMv+ppVDZjxdYMF5hz3bEVYtJRuoJIWvSJz/AB1cxUTRqKvJFLOGJ5LTDR8Rms6rFW/b/tetERE0RNEQEWffA5U/tG/+pTf5R98DlT+0b/6lN/lIfDt7G0/q8H24/GEpnQxDaaO+2Ots9wibLS1kLoZGqnQqaa9/SR398DlT+0b/AOpTf5R98DlT+0b/AOpTf5RyX9jydVp5jabx+MKlYMq6rAOc1A/witfbLt8HnVF03o9/ckT0tV3rPQg858cXGju+Zl2utvlWWkq7m+aF+6rd5jpNUXReKHowTaj1S1vB59JWO0T+4U522vKfbvopnvJC4xTnba8p9u+ime8kMdP56xxf6tPvhP2zJ5D8OfwpPevJII32ZPIfhz+FJ715JBFfzpXNL6Cnuj5AAMU6mu2vSVEOatFVyI5Yai1R+Dd0atkkRzfRwX+cT7sxXi33XJyyw0UkfhKGNaeojavFj0cq8U7UVF9J289Ms6PMnDDKTwraW6UaukoalU1RqqnFjv3XaJr1aIvRotR2MzLyWxI6VIqy1SK7dV+5v0tSidvxXJ9adhajbJSK+uGiyTfRaq2aY3rZfoFXsK7VbkbHFifDKOX9Oegl09O47/MSfhnP7LK9rGx17fbJn8o6+FY9O96asT+kQ2xXj1Njj1+nydrfj0Z3jHDlqxZhyrsF5g8NR1TN16IujmrzRzV6FRdFQw7JrKKzZZz3GpoLjV19RXI1ivnRrUYxqqqNRE6ePFexOCGfWy42+6Ujau2V1NW07viy08rZGL3K1VQ7RjzTEbJ5xY73jJMdY7SAAxSgAAAAAAAAAAAAAAAAAAAAAaK5qORqqmq8k1NSk+0dfMXWDPmvq0ulbTugdDNblbIqMSLcbpupy01RyL1qimeOnPOyprNVGmpF5jfquwDDsn8cUWPsEUl6p3NSpRqRVsKc4pkTxk06l5p2KZiYzExO0rNL1vWLV7SAA8ZBC+2Dh6luuVMl3dG34XaZ2SxSacd1zka5uvUuqL6EJoIP2x8T0tqy1SwJI1a27zNa1mvFI2KjnO7tUanpM8W/PGypruX+nvzexGOw/cpocwbxake5IKq2LM5vQr45GI1fVI4t8VK2HbLNNi6+YgVn4CloUpEcvS+R7XcO5I/rQtqZ5/PQcJif6aN/vUV2sPLvfvMpv7vGZ5hLZigv2FrVe1xpJTrX0cVSsSW1Hbm+xHbuvhE10156IYztlWiSgzdW4qx3g7lRRStdpwVzE8Gqd6IxPWhZTZ4v1Pf8oLBPA5qvpaZtHM1F1Vj4k3dF70RF9JLe9q46zVr8GnxZdZlpljfvP5ol+9Mp/wBu5f7LT/VH3plP+3cv9lp/qlmgQ+Nf2tn/AGvS/Y/Of3Vl+9Mp/wBu5f7LT/VH3plP+3cv9lp/qlmjHsb41wvgqhjrMTXeGgjlduxIrXPfIvTutaiuXTpXTgexmyT2ljbh2jrG9q7R75/d8jJrLe3ZaYdntdFWzV81TN4aoqJGIzedoiIiNTXREROtea8TODpWG7W6+2elu9oq46uhqmeEhmZro5PTxRehUXiiod0itMzO8r2OlKUitOyiW1X5eMQ91N/doi6GXn5hWD6Og92hULbDtU1BnJUVz2/g7lRwzsd5rfBqnf4n1oWiyHvtPiHKewVsD0c6KlbTzJ0tkjTdVF9WvpLGXrjrLT6D6Ory1nv/ANs4ABWbsAIQ2l84a3ALqKx4c+DuvFSzw00krd9KePXRvi8lc5UXnyROXFDKtZtO0Is+emCk3v2TeaSfJu7lMOyVxNc8YZa2rEN3gjhrKpr99I2q1rt17mo5E6NdDMZPk3dynkxtOzKl4vWLR2l57YS8tts/4hj/ALwh6FHnrhLy22z/AIhj/vCHoUWNR3hqODebf3gAKzdMD2hPIvij5n/1NKb5JYAZmPi6WwvurrYjKR9R4ZIPC67qtTTTeb+tz16C7ubNrlvWWeI7ZBGsk09vlSJic3PRquanrRCneyxfobBnJbfhT2xw17H0TnO6HPTxPW9Gp6S1hmYpOzRcSpW2qx8/aen5pR+9Mp/27l/stP8AVH3plP8At3L/AGWn+qWaBF41/avf2vS/Y/Of3Vl+9Mp/27l/stP9UfemU/7dy/2Wn+qWaC8E1UeNf2n9r0v2Pzn91c8P7K9pobzS1lxxZUV9NDI2R9OyhSJZNF13Vdvu0Renh6ixhiNnzKwPd8WvwrbcQ01Td2byeBY12jlamrka/TdcqIiroiryXqUy4xva0+cm02HBjifB/cKc7bXlPt30Uz3khcYp7tuwSMzHtVQ5qpHJbEa13WrZH6+1PWSafz1Xi/1affCetmTyH4c/hSe9eSQRlsuzRzZHYfWNyLuNmY7ToVJn8CTSK/nSuaX0FPdHyAAYpw46mngqoHwVMMc8L00fHI1HNcnUqLwUrmm0hWUWa9XYbxZ6WCxQ176JZWq7w8W6/c8I7jovFNVTTl3cbHsc17EexyOa5NUVF4Khlak17oMOox59+SeyOcT5IZZX9zpJsNQUMzv97QOWn07d1vietpGOJ9lO3va6TDWKKiByIu7DXxJIir0eOzTRP5qllQZVy3r2lHk0OnyedWPkoRiXCeZWTl4jr0lqreiuRI6+hlVYJf3VX1+K5PQWS2cs40zAp5LLe2RwYgpY99XMTRlVGmiK9E6HJqmqduqdSSXjmz0F/wAI3S03OJktNPTPRyOT4q6KqOTqVF0XXsKObPVVPb87sNupnKqurFgdp0se1zXfUupNExlpO/eGrtS2g1FIpO9bepf0AFVvwAAAAAAAAAAAAAAAAAAAAAIq2jMrmZhYaZU25kbL9b0V1K9eHhmc1iVe3miryXq1UlUHtbTWd4R5cVctJpbtLz4y9xninKnF8stPFJFI13gq+31CK1sqIvJydDk6HdHaiqi27y8zuwJi+mjb9047TXuTx6StcjFRf3XL4rk7l9CHdzTylwnmDCslyplpbk1ukdfTaNlTqR3Q5OxfRoVtxjs049tEr32NaO/UyKu6sUiQy6drHqiepylmZx5e/SWlrj1ehnakc1VzYJ4J2I+CaOVqpqisciovqNtVV0tLGslVUwwMbxV0kiNRPSp5+TYJzStLli/kziuBE4aw0syt9bU0NYMBZpXh6R/yXxRPvLoi1FNK1v8ASeiIeeBH2kn92ydvCnf+fctbmVn5gnClNJFbqtl9uaJoynpH6xov78nJE7tV7Cp11r8X5uZgNlex9fdKxyRxQxoqRwR68Gon6LE1VdV7VXipIeCtmXGl0lZLiOopLFS6+MzfSedU7Eau763egs1lrlzhfL+3LTWKi/DvTSarmXeml73dCdiaIe81MUfR6yjnDqtdaPF+jX2NMn8D0mX+CKWw07kkn18NVzJ/vZnIm8vcmiInYiGYAFaZmZ3lvKUrSsVr2hF20hly7MDBKfc9jfu1bHOnoteHhEVPHi16N5ETTtanRqViyRzOumVmJKikr6WeW1zyblfROTdkjenDfai8nJyVF58upS9xFub+SeGcwHPr2qtpvKp+OQsRUk/iN4b3fqi9pNjyREctuzW6zR3teM+GdrR+bMMHY3wri6hZVWG9UtUjk1WLfRsjOxzF4oZC5zWpvOVETrVSkl/2es0LFVOfa6SC6RtXxZqGqax2nmvVrte7U+UmXGdVUqUzrHiNzeWkk6o31q7Q98Gs9rI44jnr0vinf+fctfmZm9g7A9DKtTcYq+4oi+CoaV6Pkc795U4NTtX6yoF6uWMM58xmK2F1TW1LvB08DNfBU0SL9TU5qq8zOMIbMuOLpUNkxFU0djp1Xx0WRKiZe5rF3fW4s1lllzhnL62LSWKkVZpE/D1c2jppe9ehOxNEPYtTFHTrKOcWp11o8SOWnsd/LjDEGDcD2rDNPKsraGHddIvDfe5Vc93Yiuc5dDIACvM7zu3VaxWIrHaEUbTGXEmPcGsntsaOvNrV0tKn/qtVPHj710RU7UTrUrZkVmncsr79PQXGnnms9RJpWUmmkkMicN9qLycnJU6dOxC9RFOb+R2GcfSPuMLltF6VONVCxFbL/EZw3u9FRe1eRNjyRty27NbrNHe2SM+CdrR+bNsIY0wviyhZV2G9UlY1yaqxHokjOxzF4oveh997msarnuRrU6VXRCkV+2fM0rFVOfbKKK5xtXxZ6Cra12nmvVrte7U+azLTOqvVKR9jxA9vLdnqd1nrc5EPfBrPayOOI569L4Z3/n3LP5r514SwTQzRU1bBdrxuqkVJTyI5Gu65HJwan1lXMC4bxLnVmdNVV8sr2TTJPc6zTxYY/wBVvRrom61v+CKZ7gPZfxBW1EdTjG5QWym11fT0z0lnd2K74re9N4s7gzCtiwfZY7Rh+gjpKVnFdOLnu6XOcvFy9qnvNTHG1essYwZ9beLZ45ax6n0bTQUlqtdLbKCFsFJSxNhhjbyaxqaInqQ7Enybu5TUKmqKnWVm522jaHnrhLy22z/iGP8AvCHoUVhsmztiWizdhvslzt33Fp7l8OY9HuWZzUk32sVu7pvckVddOnsLPE+e0W22avheDJhrfnjbqAAgbUKRbSmWlZgXGMl9tcL0sdwnWankjThTSquqxrpy46q3s7lLunTvdqt16tc9sutHDWUc7d2WGVurXISY8k0ndU1ukrqcfL2mOyDMjdoCz3e201kxpVst92iakbayVdIalE5Kq/ou69eC+nQnqlqaeqhbNS1EU8bk1a+N6ORU70KxZjbL061Etbga6ReCcquShrXKit7GSIi69iOT0kZy5T5zWR6xQWG7sai6ItHVNe1f6D1JZx479azsoU1Wr08cmXHzbeuF4rpdLbaqV9Vc6+lo4GJq6SeVGInpUrPn/tA09bQVOGMCzvcyVFjqrmniorelsXTx5K71dZHFHkvnBfpmpVWOta1V4yV9YxqN7dHO3vUikwZYbMlvtlTFccbV8dzmjVHNoaZFSDX95y6K9OzRPSIrjp1md3l8+r1UcmOnLE+uWK7IOW1xqsRw4+ucL4KCjR6UKOTRaiRzVarkT9VEVePSunUpbU46aCGlp46emiZDDG1GsjY3RrUTkiInJDkIcl5vO7ZaTTV02PkgIU2tcBVWLMGQXm1wOmuFnVz1jamrpIXab6InSqaIvoUmsLxTRTytprO8JM+GubHNLdpUp2b8448vpZ7FfoppbHVS+FR8aavpZOCK7TpaqImqc004dJZ+hzby2rKds8WMbU1rk10ll3HJ3o7RUMPzP2ecKYtrZbpa55LDcZV3pHQxo+GR3Sqx6povcqekiup2VcWtmclNiOyyxa+K6RJGKvoRq6esnnw79d9mpxxrtLHhxXmj1LF/+KGXf7Z2X+tNMmtNyt92oI6+11sFZSy/Emhej2O7lQqT96vjT/56w/0pf8hYXI3Ak+XmBmWKquDa2odO+eV7EVGNV2ibrdeOnDmR3rSI+jK5ps+pyX2y02hAu11lfUW+8y49stO59BWKi3FjG6+Am5eE813SvQ7XrPsbO2fNvprTTYUxtVfB1p2pHR3B/FjmJwRki9CpyR3LTnppxszVQQVVNJTVMTJoZWqySN7UVrmrwVFReaFdcz9mSiuNVLccEV8Vukeu86hqdVh1/ccmqt7lRfQZ1vW1eW6tn0ubBlnPp/X3hYa319DcKdtRQVlPVQvTVr4ZEe1U70OSpqKemiWWpnihjamqukejUT0qUXqsnM4rDKraax3DdReD6Cra5F9DXa+tDbDlNnNe3+DnsV3e1ea1lW1jU/pvQeDX7R/cs3bwZ3+P7Jt2hs8rJQYfrMNYTro7hdKtjoZqmB2sVMxU0do5PjO04Jpy59ix/sdYFq7njL+WdXC5lutbXNp3OThLO5qt4daNaqqvarT7uXWy7U/CYq3HF0hSFqo5aGhcrlf2OkVE07Uai95Ziy2u32W1wWy1UkVJR07dyKKNujWoLXrSvLUw6fNqM0Zs8bRHaHcABXbgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAf/Z';

const METHODOLOGY = `##
How much water should I drink in a day?
Until your urine is clear. Some people need 2 liters of water, others
more, and others less. Although the general rule is 30ml per kg of
body weight, it depends on how well your kidneys are functioning.
That's why I usually recommend evaluating by the color of your urine.
In the morning, it's normal for it to be more yellow, but the goal is
to go to bed with the last urine of the day looking like water, that
is, clear! Remember that the color can vary if you are taking
medications or B-complex vitamins, so a minimum of 2 liters of water
per day is okay? It's not juice, soda, or tea, it's water! Teas can be
an additional hydration tool during the day therapeutically.
I am new to eating healthy, where should I begin?
### **The #dietitianproud Plate**
The #thedietitianproud plate is as colorful as possible with natural
ingredients, meaning avoiding processed foods and consuming more leaves,
vegetables, and fruits. Use extra virgin olive oil as the base of your
diet. For cooking, use an acidity of 0.5 (it will be written on the
olive oil bottle), and for finishing preparation like soups or adding to
salads and sauces, use an acidity of 0.4 or lower. This helps to
preserve the properties of the oil when cooking rice, grilling chicken,
for example. Prefer local, organic foods whenever possible. Drink more
digestive teas like fennel, ginger, chamomile, and lemongrass between
meals. When eating out, choose restaurants that offer fresh food, such
as sourdough bread, fresh pasta, homemade burgers, and so on. Value the
food of your region and culture! Healthy eating is not just about
nutrients; it is also about pleasure, culture, and entertainment. Avoid
fried foods and foods with INS and other chemical additives.
**Do you recommend counting calories?** I advocate for the quality of
the diet and the specification of the therapeutic properties of food for
each case. Of course, calories matter in a weight management process.
But have you ever thought about comparing a zero-calorie soda with
orange juice? The soda would seem better because it has zero calories,
but what about the quality of what you\\'re consuming? It has artificial
sweeteners and acidity that can harm your bones, stomach, and cause
inflammation. Natural orange juice, on the other hand, has more calories
but also contains vitamins, antioxidants, and can be used before a
workout to give you energy. Calories can be compensated with exercise,
inflammation cannot!
**What is the best diet for losing weight?** The best answer is: the one
you will follow and, preferably, one that is based on your genetics and
current hormonal situation. Therefore, having this data is highly
valuable for efficient weight loss and to avoid frustrations and the
famous \\"yo-yo effect.\\" For instance, some obese people have low
dopamine levels, which is our brain\\'s messenger for focus, motivation,
determination. Fat cells in large quantities inhibit this messenger,
making it so hard to stick to the diet and leading us to give up more
quickly. In such cases, a diet rich in dopamine-boosting foods will be
more effective than a ketogenic or low-carb diet.
For people with a gene called FABP2, which involves \\"stubborn fat,\\"
merely restricting calories does not work; it requires high levels of
antioxidants such as teas, berries, extra virgin olive oil, and physical
activity.
But generally, if you don\\'t know where to start, go for a diet with 30%
protein, 30% fat, and 40% carbohydrates, based on a caloric intake of 20
kcal per kg of body weight, always focusing on the quality of healthier
foods to make up this diet.
**Is diet soda really that bad for me?** Yes!!! Opt for flavored water,
sparkling water with lemon, or teas with carbonated water, but avoid
soda as much as possible. Despite having zero calories, its acidity
harms your stomach and intestines\\' ability to maintain good bacteria
capable of managing your immunity and disease prevention, as well as
nutrient absorption, and it also harms your bones.
**Should I practice intermittent fasting? I\\'m not sure if it\\'s better
to eat smaller, more frequent meals or 3 larger meals.** Fasting should
be evaluated according to the patient\\'s genetics. Generally, if you
don\\'t have your genetic test, practice fasting twice a week on
non-consecutive days, such as Tuesday and Saturday, for 16 to 18 hours
only. Do not go for 24 hours or spend days without eating. And remember
to hydrate well during fasting! Note: If you are experiencing a
significant amount of stress or have a diagnosed eating disorder, do not
fast as it can worsen your condition since the hormones released
activate cortisol and increase your stress. In the case of binge eating,
you emotionally feel deprived, and when you break the fast, you end up
making unhealthy dietary choices. Remember, the post-fasting meal should
be light, high in protein, low in fat, and sugar-free, of course, always
adding healthy foods---no burgers and fries!
**What is the recommended amount of exercise per week?** Hey! Let\\'s get
moving! Did you know that physical exercise improves blood circulation,
reduces the risk of cardiovascular diseases, helps control body weight,
and promotes physical and mental well-being, among other benefits? But
remember, don\\'t engage in an activity that you don\\'t enjoy, okay? You
can dance, cycle, lift weights, swim, play volleyball, or any activity
you like that isn\\'t a burden for you. Ideally, move your body every
day, not necessarily lifting weights every day. You can alternate with
exercises for your joints and strengthening, 2 to 3 times a week, like
Pilates. You can do aerobic exercises like walking, running, dance
classes, or martial arts, swimming, 3 times a week, but whenever
possible, include weight training, which is a complete exercise for
health, 3 times a week.
**How can I boost my metabolism?** By drinking more water, i.e., staying
well hydrated. Engaging in regular physical activity. Incre`;

const RECIPES = `

=== RECEITAS TERAPÊUTICAS: ANSIEDADE, ESTRESSE, INSÔNIA, PÂNICO, OCD, PTSD, PREOCUPAÇÃO EXCESSIVA ===
### Immunity Seasoning Mix for Anxiety
**Ingredientes:**

-   1 bunch of parsley

-   1 bunch of green onions

-   1/2 tray of thyme (only the leaves)

-   100 ml olive oil

**Modo de preparo:**

1.  Chop all the ingredients finely and process them into a paste.

2.  Store in the refrigerator for up to 2 months.

3.  Can be used as a base for various preparations: rice, meat, fish,
stir-fries, and vegetables.

### Flaxseed Gel (Egg Substitute)
**Ingredientes:**

-   1 cup flaxseeds

-   2 cups water

**Modo de preparo:**

1.  Soak the flaxseeds in water for 15 minutes.

2.  Process until it forms a gel.

3.  Can be stored in the refrigerator for up to 2 days.

### Brazil Nut Cream Cheese
**Ingredientes:**

-   1 cup broken Brazil nuts

-   1/2 cup filtered water

-   2 tablespoons olive oil

-   Juice of 1/2 lime

-   Salt to taste

**Modo de preparo:**

1.  Soak the Brazil nuts in water for at least 6 hours. Drain.

2.  Blend the soaked nuts with the other ingredients until smooth.

3.  Optionally, add fresh herbs or spices.

**Informação nutricional for 1 porção (2 tablespoons):**

-   Calories: 100 kcal

-   Carbohydrates: 2 g

-   Protein: 2 g

-   Fiber: 1 g

-   Fats: 9 g

### Savory Granola
**Ingredientes:**

-   1 cup rolled oats

-   2 tablespoons golden flaxseeds

-   1 tablespoon toasted sesame seed mix

-   1/2 tablespoon chia seeds

-   1/2 cup chopped Brazil nuts

-   2 tablespoons sliced almonds

-   1/2 cup walnuts

-   1/2 cup cashews

-   1 teaspoon rosemary

-   1 tablespoon dehydrated garlic

-   2 tablespoons dehydrated onion flakes

-   1 teaspoon thyme

-   2 tablespoons olive oil

-   Salt and black pepper to taste

**Modo de preparo:**

1.  Mix all ingredients in a bowl.

2.  Spread on a baking sheet and bake at 180°C for 10 minutes.

3.  Stir and bake for another 10 minutes.

4.  Let cool and store in an airtight container.

**Informação nutricional for 1 porção (30g):**

-   Calories: 150 kcal

-   Carbohydrates: 12 g

-   Protein: 4 g

-   Fiber: 3 g

-   Fats: 10 g

### Avocado Mayonnaise
**Ingredientes:**

-   1 medium ripe avocado

-   1/2 bunch chopped green onions

-   Juice of 1/2 lime

-   1 clove garlic, minced

-   1 tablespoon yellow mustard

-   1/2 cup olive oil

-   Salt to taste

**Modo de preparo:**

1.  Blend all ingredients except olive oil until smooth.

2.  With the blender running, slowly add the olive oil until creamy.

**Informação nutricional for 1 porção (2 tablespoons):**

-   Calories: 80 kcal

-   Carbohydrates: 2 g

-   Protein: 1 g

-   Fiber: 1 g

-   Fats: 8 g

### Herb Paste
**Ingredientes:**

-   200 g ricotta

-   2 tablespoons seasoning mix

-   50 ml almond or cashew milk

-   A pinch of salt

**Modo de preparo:**

1.  Blend all ingredients until creamy.

**Informação nutricional for 1 porção (2 tablespoons):**

-   Calories: 60 kcal

-   Carbohydrates: 1 g

-   Protein: 3 g

-   Fiber: 0 g

-   Fats: 5 g

### Chimichurri
**Ingredientes:**

-   1 bunch parsley

-   1 bunch chives

-   1 sprig rosemary

-   10 sprigs thyme

-   2 tablespoons oregano

-   5 cloves garlic, minced

-   1/2 onion

-   1 teaspoon crushed red pepper flakes (optional)

-   1 tablespoon smoked paprika

-   200 ml olive oil

-   400 ml water

-   Juice of 1 lime

-   Salt to taste

**Modo de preparo:**

1.  Finely chop herbs and onion.

2.  Mix all ingredients in a bowl, adjust salt.

3.  Store in a jar in the refrigerator.

4.  Emulsify and serve 15 minutes before use.


=== RECEITAS TERAPÊUTICAS: SAÚDE CARDIOVASCULAR, COLESTEROL ALTO, PRESSÃO ALTA, TRIGLICERÍDEOS, LDL, HDL, RISCO CARDÍACO ===
### Asian Turkey Cabbage Boats
*Rende 6 porções (1 porção ≈ ¾--1 cup)*

-   3 tablespoons fresh lime juice

-   1 tablespoon cornstarch

-   ¼ cup coconut aminos

-   1 teaspoon sesame oil

-   1 tablespoon coconut oil

-   1 pound ground turkey breast

-   1 tablespoon grated fresh ginger root

-   2 cloves fresh garlic, minced

-   1 cup (≈ 1 bunch) thinly sliced green onions

-   1 small jalapeño pepper, finely chopped (optional)

-   ½ to 1 cup sliced red bell pepper (1-inch strips)

-   1 package shredded carrots (≈ 2 cups)

-   1 package broccoli slaw (≈ 2 cups)

-   1 tablespoon chopped fresh mint

-   2 tablespoons chopped fresh cilantro

-   6 Chinese cabbage leaves, lightly steamed for 1--2 minutes

-   ¼ cup chopped almonds, roasted

#

### Directions
1.  In a small bowl, mix together fresh lime juice, cornstarch, coconut
    aminos, and sesame oil, and set aside.

2.  In a large skillet or wok, heat coconut oil over medium-high heat.
Add ground turkey breast, ginger, and garlic, and cook. Stir often
until turkey is browned and cooked through, about 6--8 minutes.

3.  Add green onions, jalapeño, bell peppers, shredded carrots, and
broccoli slaw, and stir-fry until vegetables are crisp, but
tender.

4.  Add the lime juice-cornstarch mixture to the meat and vegetables.
    Mix thoroughly, and turn down heat to low setting. Fold in chopped
    mint and cilantro.
**5.**. Arrange steamed Chinese cabbage leaves on a porção platter.
Spoon about ¾--1 cup of mixture onto each leaf.Top with chopped
almonds
> **Tips:** As an alternative to the steamed Chinese cabbage, use butter
or green leaf lettuce for lettuce wraps when porção this vegetable
rich dish. There is no need to steam if using lettuce leaves so saves
a step in the preparation.

### Balsamic Roasted Beets
*Rende 2 porções*

-   1 bunch trimmed beets (about 4 beets)

-   1 tablespoon balsamic vinegar

-   2 pinches sea salt

-   2 pinches black pepper

#

### Directions
1.  Preheat oven to 400° F.

2.  Gently scrub beets, and pat dry.Wrap in foil, and roast until tender
(about 1 hour). Let cool, then peel and dice.

3.  Place beets in a medium bowl, toss with balsamic vinegar, sea salt
and pepper, and serve.

### Black Soy Bean Cocoa Soup with Lime Zest
*Rende 4 porções*

-   1 tablespoon extra virgin olive oil

-   1 small red onion, chopped

-   3 cloves garlic, pressed

-   1 large carrot, chopped

-   1 stalk celery, chopped

-   3 cups low-sodium organic vegetable broth (or chicken broth)

-   2 tablespoons unsweetened cocoa powder

-   1 teaspoon cumin

-   1 cup canned black beans, drained and rinsed

-   1 cup canned black soy beans, drained and rinsed

-   Grated zest of 1 lime

-   2--4 tablespoons fresh cilantro, chopped

#

### Directions
1.  In a medium saucepan, heat olive oil over low heat. Add the onion
    and sauté until the onions are caramelized, for approximately 15
    minutes.

2.  Add the pressed garlic, carrots, and celery, and cook for 5 minutes
longer.

3.  Add the broth, cocoa powder, and cumin. Stir well, and simmer for 10
more minutes.

4.  Stir in the black beans and black soy beans. Add lime zest. Cook for
approximately 20 minutes longer, over low heat.

5.  Serve warm, garnished with chopped cilantro.
**Tips:** This recipe is wonderful topped with sliced avocado or fresh
guacamole but this added ingredient is not part of this nutritional
analysis.

### Chia Pomegranate Oatmeal
*Rende 2 porções*

-   1⅓ cups water

-   ⅔ cup rolled oats (old fashioned)

-   1 pinch sea salt

-   ½ cup liquid egg whites

-   ½ teaspoon cinnamon

-   2 teaspoons chia seeds

-   ½ cup pomegranate seeds

#


=== RECEITAS TERAPÊUTICAS: DEPRESSÃO, HUMOR BAIXO, MOTIVAÇÃO, DOPAMINA, SEROTONINA, NÉVOA MENTAL ===
### Immunity Seasoning Mix
**Ingredientes:**

-   100 g fresh ginger

-   100 g turmeric root

-   5 cloves of garlic

-   100 ml olive oil

**Modo de preparo:**

1.  Peel the ginger, turmeric, and garlic.

2.  Finely chop all ingredients and process into a paste.

3.  Store in the refrigerator for up to 2 months.

4.  Use as a base for various preparations: rice, meat, fish,
stir-fries, and vegetables.

### Vegan Bread
**Ingredients for 1 porção:**

-   20 g oat flour

-   10 g almond flour

-   5 g chia flour

-   1 tablespoon flaxseed gel

-   1/4 teaspoon xanthan gum

-   1/4 teaspoon psyllium husk

-   1/4 teaspoon salt

-   20 ml olive oil or avocado oil

-   20 ml water

**Modo de preparo:**

1.  Mix the dry ingredients in a bowl.

2.  In another bowl, mix the flaxseed gel with olive oil and water. Add
the dry ingredients and mix to combine.

3.  Pour into a small greased bread pan and bake in a preheated oven at
180°C for 30-40 minutes.

4.  Let cool before slicing.

**Informação nutricional for 1 porção:**

-   Calories: 120 kcal

-   Carbohydrates: 6 g

-   Protein: 3 g

-   Fiber: 2 g

-   Fats: 10 g

### Flaxseed Gel (Egg Substitute)
**Ingredientes:**

-   1 cup flaxseeds

-   2 cups water

**Modo de preparo:**

1.  Soak the flaxseeds in water for 15 minutes.

2.  Process until it forms a gel.

3.  Can be stored in the refrigerator for up to 2 days.

### Tofu and Carrot Spread
**Ingredients for 1 porção:**

-   50 g tofu

-   1 tablespoon olive oil

-   A pinch of salt

-   Zest of 1/4 lime

-   1/4 carrot, grated

**Modo de preparo:**

1.  Blend the tofu, olive oil, salt, and lime zest until smooth.

2.  Stir in the grated carrot.

**Informação nutricional for 1 porção:**

-   Calories: 70 kcal

-   Carbohydrates: 2 g

-   Protein: 3 g

-   Fiber: 1 g

-   Fats: 6 g

### Whey Protein Shake
**Ingredients for 1 porção:**

-   250 ml cold almond milk

-   1/2 banana

-   1 tablespoon vanilla whey protein

-   1/4 teaspoon matcha

-   1 tablespoon 100% cocoa powder

-   1 tablespoon molasses

**Modo de preparo:**

1.  Blend all ingredients and serve cold.

**Informação nutricional for 1 porção:**

-   Calories: 150 kcal

-   Carbohydrates: 20 g

-   Protein: 12 g

-   Fiber: 4 g

-   Fats: 3 g


=== RECEITAS TERAPÊUTICAS: DETOX, DESINTOXICAÇÃO, FÍGADO, ENZIMAS HEPÁTICAS ALTERADAS, TOXINAS, ESTEATOSE ===
### Almond Cocoa Smoothie
*Rende 2 porções*

-   2 cups unsweetened almond milk

-   1 scoop vegan protein powder\\*

-   1 small avocado

-   1 tablespoon cocoa powder

-   1 teaspoon almond extract

-   ½ cup ice cubes

-   Stevia, to taste (optional)

-   1--2 cups loosely packed chopped kale
*\\*Soy-free.Typical varieties include rice, pea, hemp. Should be
sweetened with stevia or unsweetened altogether. 1 scoop should be ≈
17g protein.*

#

### Directions
1.  Put all ingredients in a blender in the order listed.

2.  Blend all ingredients together in a blender starting on low speed
and working up to high speed until smooth.

3.  Add more or less ice to desired thickness.

### Asian Salad
*Rende 10 porções (1 porção ≈ ½--¾ cup)*
> **Salad:**

-   1 medium head Napa cabbage, end cut off & cut into quarters

-   8 ounces bean sprouts

-   1 small jicama or daikon, peeled & sliced into thin pieces

-   1 bunch green onions, thinly sliced, dark green ends discarded

-   1 large red bell pepper, cut in half & sliced very thin

-   1 stalk celery, sliced very thin

-   ½ cup slivered almonds

-   1 bunch cilantro, chopped (set aside several tablespoons for
    garnish)
**Dressing:**

-   ⅔ cup grapeseed or olive oil

-   ⅓ cup rice vinegar\\*

-   1 tablespoon sesame oil

-   3 tablespoons Dijon mustard

-   1 clove garlic, minced

-   3-inch piece fresh ginger

-   1 teaspoon agave syrup

-   2 pinches salt

-   2 pinches black pepper
*\\*Be sure to use unseasoned rice vinegar (no sugar added).*

#

### Directions
1.  Whisk all dressing ingredients together and set aside.This can be
    made up to several days ahead of time and stored in the
    refrigerator.

2.  Prepare the salad: **a.** Slice each quarter of cabbage very thin
    and place into a large porção bowl.

**b.** Add bean sprouts, jicama or daikon, green onion, pepper and
celery and mix well to combine.

3.  Add half the cilantro and half the dressing and toss well. Allow to
sit for a few minutes to blend.

4.  Just prior to porção toss in almonds and garnish with remaining
    cilantro.
**Tips:** Add more dressing as needed, being careful not to make it
too wet. The salad will become wetter as it sits; wait until porção
before adding more if needed. Refrigerate if not porção immediately.

### Asparagus and Kohlrabi Salad
*Rende 6 porções (1 porção ≈ 1⅔ cup arugula and ⅔ cup asparagus
mixture)*

-   1 pound asparagus, ends discarded

-   2 medium Kohlrabi, peeled

-   2 tablespoons olive oil, divided

-   ¼ pound arugula (or use ½ pound watercress)

-   2 teaspoons balsamic vinegar

-   1 pinch salt

-   1 pinch black pepper

#

### Directions
1.  Cut asparagus stalks into ¼-inch diagonal slices, separating tips.
    Prepare kohlrabi by slicing in ½-inch strips.

2.  In a wok or large sauté pan, stir-fry asparagus stalks and kohlrabi
in
1 tablespoon olive oil over medium heat until slightly browned. Add
asparagus tips and continue to stir-fry for another 4--5 minutes.
Remove from heat and toss with salt and pepper.

3.  Pile arugula (or watercress) in a salad bowl and toss with remaining
1 tablespoon olive oil.Top with asparagus and kohlrabi, and
drizzle with balsamic vinegar. Serve immediately.

### Balsamic Mustard Vinaigrette
*Rende 10 porções (1 porção ≈ 2 tablespoons)*

-   ¼ cup balsamic vinegar

-   ¼ cup water

-   1 teaspoon Dijon mustard

-   Herbs to taste\\*

-   1 pinch sea salt

-   1 pinch black pepper

-   1 clove garlic, minced

-   ⅓ cup cold-pressed, extra-virgin olive oil

-   ⅓ cup flaxseed oil (or use all olive oil)
*\\*Use dried rosemary, oregano, basil, parsley, tarragon, or any herb
of choice.*

#


=== RECEITAS TERAPÊUTICAS: CANSAÇO, FADIGA, ENERGIA BAIXA, ANEMIA, TIREOIDE, HIPOTIREOIDISMO, FERRO BAIXO, B12 ===
### Avocado Lime Soup
*Rende 6 porções (1 porção ≈ 1 cup)*

-   ¼ cup fresh lime juice (juice of 2 limes)

-   1½ cup cucumber chunks

-   1 stalk celery

-   6 leaves Romaine lettuce

-   1 avocado

-   ¼ cup fresh cilantro

-   2 cups water

-   ½ teaspoon sea salt

-   ½ teaspoon cumin

#

### Directions
1.  Using blender or food processor, blend together all ingredients
    until smooth.

2.  Serve cold. Garnish with extra chopped cilantro, if desired.
**Tip:** For a variation, substitute the juice of 1 lemon for the lime
juice, parsley for the cilantro, and hold the cumin.

### Baby Greens with Blackberry Vinaigrette
*Rende 2 porções*
> **Dressing:**

-   ¼ cup fresh or frozen blackberries (defrost if frozen)

-   1 teaspoon coarsely chopped shallots

-   1 tablespoon extra-virgin olive oil

-   2 teaspoons fresh lemon juice

-   1 teaspoon balsamic vinegar

-   ¼ teaspoon Dijon-style mustard

-   1 pinch sea salt

-   1 pinch freshly ground pepper
**Salad:**

-   4 cups lightly packed mesclun salad mix

-   2 tablespoons crumbled fresh goat cheese

-   3 tablespoons chopped walnuts

#

### Directions
1.  Place all dressing ingredients in blender or mini food processor and
    blend until dressing is creamy and smooth. Let dressing stand in
    refrigerator for up to 24 hours before using.

2.  When ready to serve salad, divide salad greens between 2 plates. Add
    goat cheese, then drizzle 2 tablespoons of dressing over each
    salad.Top with chopped walnuts.

-   **Mito-Ketoflex and dairy-free options:** Omit goat cheese and
    prepare as directed. Substitute cashew cheese for goat cheese if
    desired. Note that nutritional analysis is calculated with dairy
    ingredients included.

### Baked Spinach Omelet
*Rende 8 porções (1 porção = one 3-inch by 4-inch piece)*

-   ¼ cup butter

-   1 pound fresh spinach, washed

-   ¼ teaspoon salt

-   ¼ teaspoon pepper

-   8 large eggs, beaten

-   ¾ cup whole milk ricotta

-   ½ cup heavy cream

-   1 tablespoon chopped fresh basil (or ½ teaspoon dried basil)

-   ¾ cup chopped plum tomatoes

-   ¾ cup shredded whole milk mozzarella

-   ¼ cup thinly sliced scallions

#

### Directions
1.  Preheat oven to 325° F.

2.  Melt butter in large skillet. Add fresh spinach, salt, and pepper.
    Cook spinach until wilted. Set aside.

3.  In a large mixing bowl, combine eggs and ricotta. Stir in cream and
basil. Fold in spinach, tomato, mozzarella, and scallions. Spread
evenly in a greased baking dish (2-quart casserole or 12-inch by
8-inch dish or equivalent).

4.  Bake for 30--35 minutes or until a knife inserted near the center
    comes out clean. Allow to stand for 10--15 minutes before porção.
**Tip:** This omelet makes a nice brunch dish and includes
brain-healthy spinach. In place of 1 pound of fresh spinach, you could
use a 10 ounce box of frozen spinach (thawed and squeezed dry).

-   **Mito-Ketoflex and dairy-free options:** Omit ricotta and
    mozzarella cheese, and substitute with almond or cashew cheese, if
    desired. Substitute canned coconut milk for heavy cream and coconut
    oil for butter.
Omitting dairy still results in a vegetable omelet that tastes
wonderful. Note that the nutrition analysis above includes the dairy
ingredients.

### Basic Greens
*Rende 6 porções (1 porção ≈ ½ cup)*

-   1 large bunch kale, collard greens, or bok choy, washed

-   2--3 cloves garlic, minced or cut into slivers

-   1 tablespoon olive or coconut oil

-   ½ cup low-sodium vegetable or chicken broth

#


=== RECEITAS TERAPÊUTICAS: SAÚDE FEMININA, TPM, MENOPAUSA, ENDOMETRIOSE, SOP, HORMÔNIOS, FERTILIDADE, CICLO MENSTRUAL ===
### STOVE-TOP GRANOLA
Ingredients for 1 porção:

-   2 tablespoons shelled pumpkin seeds

-   2 tablespoons unsweetened shredded coconut

-   2 tablespoons cacao nibs or chopped almonds or walnuts

-   2 tablespoons golden flaxseed meal

-   3 tablespoons rolled oats

-   ½ teaspoon coconut oil

-   ½ teaspoon honey or molasses (optional)

Preparation: Toast the oats in a skillet with coconut oil until lightly
browned. Add the pumpkin seeds and toast until yellowish. Add the
coconut and stir until it starts to brown. Turn off the heat and mix in
the flaxseed meal, cacao nibs, and honey. Let it cool and store in a
glass jar in the refrigerator.

Benefits: Granola is an excellent source of fiber, protein, and healthy
fats, along with antioxidants from the cacao nibs.

Macronutrients per porção:

-   Calories: 261.55 kcal

-   Carbohydrates: 24.27 g

-   Proteins: 7.59 g

-   Fats: 16.34 g

-   Fiber: 6.97 g

### TOFU YOGURT
Ingredients for 1 porção:

-   4-5 organic strawberries or ¼ cup other red fruits

-   ½ frozen banana

-   25 ml plant-based milk or water (used coconut milk)

-   50 g organic tofu

-   1 teaspoon golden flaxseed

Preparation: Blend all ingredients in a blender. Serve with a teaspoon
of toasted pumpkin seeds on top.

Benefits: Tofu is rich in phytoestrogens, helping with hormonal
modulation. It is important to use organic tofu to avoid pesticides.

Macronutrients per porção:

-   Calories: 78.05 kcal

-   Carbohydrates: 3.13 g

-   Proteins: 5.40 g

-   Fats: 5.55 g

-   Fiber: 2.18 g

### PUMPKIN SEED MILK
Ingredients for 1 porção:

-   ¼ cup shelled pumpkin seeds

-   1 cup warm water

-   A pinch of salt

-   ¼ teaspoon natural vanilla extract

-   ½ tablespoon white or black raisins

Preparation: Soak the pumpkin seeds in water for 4-8 hours. Rinse and
blend with warm water and raisins for about 5 minutes. Strain and mix in
the salt and vanilla. Store in the refrigerator for up to 3 days.

Benefits: Rich in essential nutrients, pumpkin seed milk is a great
plant-based alternative with anti-inflammatory properties.

Macronutrients per porção:

-   Calories: 267.6 kcal

-   Carbohydrates: 32.58 g

-   Proteins: 14.7 g

-   Fats: 11.64 g

-   Fiber: 3.9 g

### GOLDEN MILK FOR A GOOD MOOD
Ingredients for 1 porção:

-   250 ml oat milk

-   ¼ teaspoon turmeric powder

-   A pinch of cinnamon powder

-   A pinch of ginger powder

-   ¼ teaspoon maca powder

-   1 teaspoon golden flaxseed meal

-   1 teaspoon honey

Preparation: Heat the milk and mix in all the ingredients. Use a mixer
for a creamier texture.

Benefits: This golden milk is known to improve mood and libido, and help
prevent postpartum and menopause-related depression. Turmeric and maca
are potent anti-inflammatories and mood regulators.

Macronutrients per porção:

-   Calories: 126.25 kcal

-   Carbohydrates: 19.25 g

-   Proteins: 2.06 g

-   Fats: 5.595 g

-   Fiber: 4.71 g

### CARROT AND COCONUT PANCAKE
Ingredients for 1 porção:

-   2 tablespoons oat flour

-   1 teaspoon flaxseed meal

-   1 teaspoon ground pumpkin seeds

-   1 tablespoon unsweetened shredded coconut

-   2 tablespoons grated organic carrot

-   2 tablespoons water

-   A pinch of salt

-   A pinch of cinnamon powder

-   1 teaspoon coconut sugar or molasses

Preparation: Mix all ingredients by hand or in a blender. Pour
approximately 2 tablespoons of batter into a lightly greased skillet
with coconut oil. Cook over low heat and flip when the edges lift from
the pan.

Benefits: These pancakes are an excellent source of fiber and healthy
fats, rich in beta-carotene from the carrot, which is a natural
antioxidant.

Macronutrients per porção:

-   Calories: 164.0 kcal

-   Carbohydrates: 19.0 g

-   Proteins: 3.6 g

-   Fats: 8.5 g

-   Fiber: 4.5 g

### FIRST PHASE BREAD
Ingredients for 1 porção (2 slices):

-   1 tablespoon shelled raw pumpkin seeds (6.25 g)

-   1 tablespoon coconut flour (7.5 g)

-   1 tablespoon fine or medium rolled oats (3.125 g)

-   1 tablespoon brown rice flour (4.375 g)

-   1 teaspoon ground flaxseed (3.3 g)

-   ⅛ teaspoon psyllium (0.625 g)

-   ¼ teaspoon baking powder

-   ¼ teaspoon yeast

-   ¼ teaspoon brown sugar (1.25 g)

-   A pinch of salt

-   ¼ cup water

-   ¼ teaspoon apple cider vinegar

Preparation: Mix all dry ingredients, except the yeast. Dissolve the
yeast in warm water and let it grow. Add the activated yeast to the
dough along with the rest of the water. Let it rest and bake in a
preheated oven at 180ºC.

Benefits: This bread is rich in fiber and healthy fats from the seeds
and flours, aiding digestive and hormonal health.

Macronutrients per porção (2 slices):

-   Calories: 184.25 kcal

-   Carbohydrates: 23.5 g

-   Proteins: 5.5 g

-   Fats: 8.0 g

-   Fiber: 6.0 g

### DETOX PESTO
Ingredients for 1 porção:

-   ⅙ bunch parsley

-   ⅙ bunch cilantro (or another ⅙ bunch parsley)

-   3 basil leaves

-   1½ teaspoons extra virgin olive oil

-   1½ teaspoons macadamia or avocado oil, or more olive oil

-   1½ teaspoons toasted shelled pumpkin seeds

-   ½ teaspoon cranberry or a small slice of apple

-   ½ teaspoon lemon juice

-   A pinch of salt

Preparation: Blend all ingredients in a blender until smooth. Store in a
glass jar in the refrigerator.

Benefits: This pesto is rich in antioxidants and healthy fats, aiding in
body detoxification and cardiovascular health.

Macronutrients per porção:

-   Calories: 132.5 kcal

-   Carbohydrates: 1.0 g

-   Proteins: 1.0 g

-   Fats: 14.5 g

-   Fiber: 0.5 g


=== RECEITAS TERAPÊUTICAS: DOENÇAS AUTOIMUNES, HASHIMOTO, LÚPUS, ARTRITE REUMATOIDE, ESCLEROSE MÚLTIPLA, DOENÇA DE CROHN ===
### Immunity Mix Seasoning
**Ingredients for 1 porção:**

-   15 g fresh ginger

-   15 g turmeric root

-   1 clove of garlic

-   15 ml olive oil

**Modo de preparo:**

1.  Peel the ginger, turmeric, and garlic.

2.  Combine all ingredients and process into a paste.

3.  Store in the refrigerator for up to 2 months.

4.  This paste can be used as a base for various dishes such as rice,
meat, fish, stir-fries, and vegetables.

**Informação nutricional for 1 porção (approximately 1 tablespoon or
15 g):**

-   Calories: 70 kcal

-   Carbohydrates: 3 g

-   Protein: 0.5 g

-   Fiber: 1 g

-   Fats: 7 g

### Flaxseed Gel (Egg Substitute)
**Ingredients for 1 porção:**

-   15 g flaxseeds

-   30 ml water

**Modo de preparo:**

1.  Soak the flaxseeds in water for 15 minutes, then process until it
forms a gel.

2.  Store in the refrigerator for up to 2 days.

**Informação nutricional for 1 porção (approximately 1 tablespoon or
15 g):**

-   Calories: 25 kcal

-   Carbohydrates: 1 g

-   Protein: 1 g

-   Fiber: 2 g

-   Fats: 2 g

### Cashew Cream Cheese
**Ingredients for 1 porção:**

-   15 g raw, unsalted cashews

-   7.5 ml filtered water

-   1 teaspoon olive oil

-   Juice of 1/4 lime

-   Salt to taste

**Modo de preparo:**

1.  Soak the cashews in water until covered for at least 6 hours.

2.  Drain the water and blend the cashews with the remaining ingredients
until smooth.

3.  Optional: Add fresh herbs or spices to taste.

**Informação nutricional for 1 porção (approximately 2 tablespoons
or 30 g):**

-   Calories: 75 kcal

-   Carbohydrates: 3.5 g

-   Protein: 1.5 g

-   Fiber: 0.5 g

-   Fats: 6.5 g

### Avocado Mayonnaise
**Ingredients for 1 porção:**

-   25 g ripe avocado

-   5 g chopped parsley

-   Juice of 1/8 lime

-   1/4 clove of garlic, minced

-   1 teaspoon yellow mustard

-   7.5 ml olive oil

-   Salt to taste

**Modo de preparo:**

1.  In a blender, combine all ingredients except the olive oil and blend
for a few minutes.

2.  While blending, gradually add the olive oil until a creamy
consistency is achieved.

**Informação nutricional for 1 porção (approximately 2 tablespoons
or 30 g):**

-   Calories: 75 kcal

-   Carbohydrates: 1 g

-   Protein: 0.5 g

-   Fiber: 1 g

-   Fats: 7 g

### Tofu Mayonnaise
**Ingredients for 1 porção:**

-   30 g tofu

-   1 tablespoon olive oil

-   A pinch of salt

-   Zest of 1/4 lime

**Modo de preparo:**

1.  Blend all ingredients in a food processor or mixer until creamy.

**Informação nutricional for 1 porção (approximately 2 tablespoons
or 30 g):**

-   Calories: 45 kcal

-   Carbohydrates: 0.5 g

-   Protein: 1 g

-   Fiber: 0.5 g

-   Fats: 4 g

### Chimichurri
**Ingredients for 1 porção:**

-   2 g parsley

-   2 g chives

-   0.5 g rosemary

-   1 g thyme

-   1/4 teaspoon oregano

-   1 clove of garlic, minced

-   2 g onion

-   A pinch of red pepper flakes

-   1/4 teaspoon smoked paprika

-   15 ml olive oil

-   30 ml water

-   3.75 ml red wine vinegar

-   Salt to taste

**Modo de preparo:**

1.  Finely chop the herbs and onion.

2.  In a bowl, combine all ingredients, mix well, and adjust salt to
taste.

3.  Store in a jar and refrigerate. Let sit at room temperature for 15
minutes before porção, stirring well.

**Informação nutricional for 1 porção (approximately 2 tablespoons
or 30 g):**

-   Calories: 70 kcal

-   Carbohydrates: 1 g

-   Protein: 0.5 g

-   Fiber: 1 g

-   Fats: 7 g

### Skillet Bread
**Ingredients for 1 porção:**

-   1 tablespoon oat flour

-   1/2 tablespoon flaxseed gel (see recipe)

-   1/2 teaspoon baking powder

-   A pinch of salt

-   A dash of olive oil

**Modo de preparo:**

1.  Mix the flaxseed gel with the salt, then add the flour and finally
the baking powder.

2.  Heat a non-stick skillet and pour the mixture over low heat.

3.  Brown on both sides and serve.

4.  Suggested accompaniment: unsweetened peanut butter and nuts
(walnuts, macadamia, sunflower seeds).

**Informação nutricional for 1 porção (1 bread):**

-   Calories: 50 kcal

-   Carbohydrates: 6 g

-   Protein: 1.5 g

-   Fiber: 1 g

-   Fats: 2 g


=== RECEITAS TERAPÊUTICAS: INFLAMAÇÃO INTESTINAL, GASTRITE, REFLUXO, INTESTINO IRRITÁVEL, PERMEABILIDADE INTESTINAL, DISBIOSE ===
### Directions
1.  Put all ingredients in a blender in the order listed.

2.  Blend, starting on low speed and working up to high speed, until
smooth.
**Tips:** Discuss protein powders with your healthcare provider.
Suggested varieties can include quality sources of bovine collagen,
pea, egg white, or hemp proteins. Use frozen berries instead of ice to
make smoothie cold and of desired thickness. (Frozen berries are not
included in the nutritional analysis.)

# Asian Beef Lettuce Wraps
*Rende 4 porções (1 porção ≈ 3 lettuce wraps)*
> ***(if beef is omitted)***

-   1 tablespoon gluten-free tamari or coconut aminos

-   ¼ cup apple cider vinegar

-   2 tablespoon fresh lime juice

-   ¼ teaspoon sea salt

-   16 ounces grass-fed beef (organic preferred)

-   1 teaspoon sesame oil

-   ½ cup finely chopped onion

-   3 cloves garlic, minced

-   1 tablespoon peeled and minced fresh ginger

-   1½ cup carrots, cut into `;

const SINTS = ['🤕 Dor de cabeça','😴 Insônia','🔥 Gastrite / Refluxo','💨 Inchaço / Gases','😰 Ansiedade','😔 Depressão / Humor baixo','🩸 Colesterol alto','🍬 Glicemia elevada','⚡ Cansaço / Fadiga','🫀 Pressão alta','🦴 Dores articulares','🧠 Névoa mental','🌸 TPM / Hormonal','⚖️ Emagrecer','💪 Ganhar massa','🦠 Intestino irregular','🔬 Fígado / Enzimas alt.','🦋 Tireoide','🛡️ Doenças autoimunes','🩺 Desintoxicação / Detox'];
const DIETS = ['🌿 Vegano','🥚 Vegetariano','🌾 Sem glúten','🥛 Sem leite e derivados','🫙 Sem lactose','🥗 Low carb','💪 Alto em proteína','🥑 Cetogênico','🌊 Baixo em histamina','🫘 Low FODMAP','🐟 Pescetariano','🩺 Anti-inflamatório'];
const MEALS = ['☀️ Café da manhã','🍎 Lanche da manhã','🍲 Almoço','🫐 Lanche da tarde','🌙 Jantar','🌛 Ceia'];

export default function App() {
  const [screen, setScreen] = useState('welcome');
  const [tab, setTab] = useState(0);
  const [loading, setLoading] = useState(false);
  const [result, setResult] = useState('');
  const [err, setErr] = useState('');
  const [pdf, setPdf] = useState(null);
  const [pdfName, setPdfName] = useState('');
  const [drag, setDrag] = useState(false);
  const [nome, setNome] = useState('');
  const [idade, setIdade] = useState('');
  const [peso, setPeso] = useState('');
  const [altura, setAltura] = useState('');
  const [meta, setMeta] = useState('');
  const [sexo, setSexo] = useState('');
  const [atv, setAtv] = useState('');
  const [sintTxt, setSintTxt] = useState('');
  const [extras, setExtras] = useState('');
  const [sintSel, setSintSel] = useState([]);
  const [dietSel, setDietSel] = useState([]);
  const [mealSel, setMealSel] = useState([]);
  const [sub, setSub] = useState('');
  const [chatOpen, setChatOpen] = useState(false);
  const [chatMsgs, setChatMsgs] = useState([{role:'assistant',text:'Olá! 👋 Sou a ANA, sua assistente de nutrição terapêutica. Posso tirar dúvidas sobre nutrição, sugerir alimentos e receitas terapêuticas. Como posso ajudar?'}]);
  const [chatInput, setChatInput] = useState('');
  const [chatLoading, setChatLoading] = useState(false);
  const chatEndRef = useRef(null);

  useEffect(() => {
    if (chatOpen) chatEndRef.current?.scrollIntoView({behavior:'smooth'});
  }, [chatMsgs, chatOpen]);

  const tog = (arr, set, v) => set(arr.includes(v) ? arr.filter(x=>x!==v) : [...arr, v]);

  const procPdf = f => {
    if (!f || f.type !== 'application/pdf') return;
    setPdfName(f.name);
    const r = new FileReader();
    r.onload = e => setPdf(e.target.result.split(',')[1]);
    r.readAsDataURL(f);
  };

  const SYSTEM_PROMPT = `Você é a ANA (Assistente de Nutrição Avançada), especialista em nutrição terapêutica funcional criada pela equipe da Nutri Secrets.

METODOLOGIA DA DRA. ALINE QUISSAK / NUTRI SECRETS:
${METHODOLOGY}

BANCO DE RECEITAS TERAPÊUTICAS (use estas receitas quando relevante):
${RECIPES}

REGRAS:
- Responda SEMPRE em português brasileiro
- Seja acolhedora, científica e prática
- Use as receitas do banco acima quando fizer sentido para os sintomas do paciente
- Traduza os nomes das receitas para português quando mencionar
- No chat: respostas concisas (máx 3 parágrafos)
- Para cardápios: use as receitas do banco como base, adaptando para os sintomas
- Nunca faça diagnósticos médicos`;

  const sendChat = async () => {
    if (!chatInput.trim() || chatLoading) return;
    const msg = chatInput.trim();
    setChatInput('');
    setChatMsgs(p => [...p, {role:'user', text:msg}]);
    setChatLoading(true);
    try {
      const history = chatMsgs.map(m => ({role: m.role==='assistant'?'assistant':'user', content: m.text}));
      history.push({role:'user', content: msg});
      const r = await fetch('/api/gerar', {
        method:'POST', headers:{'Content-Type':'application/json'},
        body: JSON.stringify({model:'claude-sonnet-4-20250514', max_tokens:700, system: SYSTEM_PROMPT, messages: history})
      });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error?.message||'Erro');
      setChatMsgs(p => [...p, {role:'assistant', text: d.content.map(c=>c.text||'').join('')}]);
    } catch(e) {
      setChatMsgs(p => [...p, {role:'assistant', text:'Desculpe, tive um problema. Tente novamente! 🙏'}]);
    }
    setChatLoading(false);
  };

  const buildPrompt = () => {
    let bmi='', tmb='';
    if (peso && altura) {
      const h = parseFloat(altura)/100;
      bmi = 'IMC: '+(parseFloat(peso)/(h*h)).toFixed(1);
      tmb = sexo.includes('Fem')
        ? (655.1+9.563*+peso+1.85*+altura-4.676*(+idade||30)).toFixed(0)
        : (66.5+13.75*+peso+5.003*+altura-6.755*(+idade||30)).toFixed(0);
    }
    return `${SYSTEM_PROMPT}

PACIENTE: ${nome||'Paciente'} | ${sexo||'?'} | ${idade||'?'} anos | ${peso||'?'}kg | ${altura||'?'}cm | ${bmi}
TMB estimada: ${tmb?tmb+' kcal/dia':'não calculado'} | Atividade: ${atv||'?'} | Meta perda: ${meta?meta+'kg':'nenhuma'}
Exame de sangue: ${pdf?'PDF ANEXADO — analise todos os marcadores laboratoriais':'não enviado'}
Sintomas/Queixas: "${sintTxt||'não informado'}" + chips: ${sintSel.join(', ')||'nenhum'}
Restrições alimentares: ${dietSel.join(', ')||'nenhuma'}
Refeições desejadas: ${mealSel.join(', ')}
Observações extras: ${extras||'nenhuma'}

GERE O CARDÁPIO TERAPÊUTICO PERSONALIZADO em português seguindo esta estrutura:

## 🔍 Análise Terapêutica Personalizada
Analise os sintomas${pdf?', o exame de sangue':''} e correlacione com deficiências nutricionais e condições identificadas. Cite a base científica.

## 📊 Perfil Nutricional Recomendado
- Meta calórica diária e método de cálculo
- Distribuição de macros (%)
- Micronutrientes prioritários com justificativa

---

## 🌿 Cardápio Terapêutico Diário
IMPORTANTE: Use as receitas do banco de receitas terapêuticas quando possível, adaptadas para os sintomas do paciente.
Para cada refeição (${mealSel.join(', ')}):

### [Nome da refeição] — [horário sugerido]
**Sugestão:** [preparação completa e gostosa com quantidades]
**Receita terapêutica:** [se usar uma receita do banco, inclua ingredientes e modo de preparo completo em português]
**Por que é terapêutico:** [mecanismo de ação para os sintomas do paciente]

---

## 🍵 Chás e Fitoterápicos
4-5 opções com evidência científica: benefício específico para os sintomas, preparo, horário, precauções.

---

## 🏃 Hábitos de Vida Terapêuticos
Exercícios ideais, meditação, higiene do sono, vitamina D, gestão de estresse, hidratação.

---

## 📝 Lista de Compras Terapêutica
Organize por categoria com os itens necessários para as receitas sugeridas.`;
  };

  const generate = async () => {
    if (!sintTxt && sintSel.length===0) {setErr('Descreva seus sintomas ou selecione ao menos um.'); return;}
    if (mealSel.length===0) {setErr('Selecione ao menos uma refeição.'); setTab(2); return;}
    setErr(''); setTab(3); setLoading(true); setResult('');
    try {
      const msgs = pdf
        ? [{role:'user',content:[{type:'document',source:{type:'base64',media_type:'application/pdf',data:pdf}},{type:'text',text:buildPrompt()}]}]
        : [{role:'user',content:buildPrompt()}];
      const r = await fetch('/api/gerar', {
        method:'POST', headers:{'Content-Type':'application/json'},
        body: JSON.stringify({model:'claude-sonnet-4-20250514', max_tokens:6000, messages:msgs})
      });
      const d = await r.json();
      if (!r.ok) throw new Error(d.error?.message||'Erro '+r.status);
      setResult(d.content.map(c=>c.text||'').join('\n'));
      setSub(`${nome||'Paciente'} · ${peso?peso+'kg':''} · ${dietSel.slice(0,2).join(', ')||'sem restrições'} · ${mealSel.join(', ')}`);
    } catch(e) {setTab(2); setErr('Erro: '+e.message);}
    finally {setLoading(false);}
  };

  const fmt = t => t
    .replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;')
    .replace(/^---$/gm,'<hr style="border:none;border-top:1.5px solid #E0F7F8;margin:22px 0">')
    .replace(/^## (.+)$/gm,'<h2>$1</h2>').replace(/^### (.+)$/gm,'<h3>$1</h3>')
    .replace(/\*\*(.+?)\*\*/g,'<strong>$1</strong>').replace(/\*(.+?)\*/g,'<em>$1</em>')
    .replace(/^- (.+)$/gm,'<li>$1</li>').replace(/(<li>[\s\S]*?<\/li>\n?)+/g,'<ul>$&</ul>')
    .replace(/\n\n+/g,'</p><p>').replace(/\n/g,'<br>')
    .replace(/^(?!<[huolp\/hr])(.+)/gm,'<p>$1</p>').replace(/<p><\/p>/g,'');

  const Chip = ({v,sel,onTog,meal}) => (
    <span onClick={()=>onTog(v)} style={{display:'inline-flex',alignItems:'center',gap:6,padding:'8px 14px',borderRadius:100,border:`1.5px solid ${sel.includes(v)?(meal?'#F97316':'#0ABDC0'):'#d0e8e8'}`,background:sel.includes(v)?(meal?'#F97316':'#0ABDC0'):'white',color:sel.includes(v)?'white':'#5a7272',cursor:'pointer',fontSize:'0.8rem',fontWeight:500,userSelect:'none',transition:'all 0.2s',margin:'0 4px 8px 0'}}>{v}</span>
  );
  const SChip = ({v,cur,set}) => (
    <span onClick={()=>set(v)} style={{display:'inline-flex',alignItems:'center',gap:6,padding:'8px 14px',borderRadius:100,border:`1.5px solid ${cur===v?'#0ABDC0':'#d0e8e8'}`,background:cur===v?'#0ABDC0':'white',color:cur===v?'white':'#5a7272',cursor:'pointer',fontSize:'0.8rem',fontWeight:500,userSelect:'none',transition:'all 0.2s',margin:'0 4px 8px 0'}}>{v}</span>
  );
  const prog = (step) => (
    <div style={{display:'flex',alignItems:'center',gap:6,marginBottom:24}}>
      {[['1','Dados'],['2','Sintomas'],['3','Preferências'],['✨','Cardápio']].map(([n,l],i)=>(
        <span key={i} style={{display:'contents'}}>
          <div style={{display:'flex',alignItems:'center',gap:6}}>
            <div style={{width:28,height:28,borderRadius:'50%',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'0.75rem',fontWeight:700,border:`2px solid ${i<step?'#0ABDC0':i===step?'#0ABDC0':'#d0e8e8'}`,background:i<step?'#0ABDC0':i===step?'white':'white',color:i<step?'white':i===step?'#0ABDC0':'#5a7272',boxShadow:i===step?'0 0 0 3px rgba(10,189,192,0.18)':'none'}}>{i<step?'✓':n}</div>
            <span style={{fontSize:'0.72rem',color:i<=step?'#078b8e':'#5a7272',fontWeight:500}}>{l}</span>
          </div>
          {i<3&&<div style={{flex:1,height:2,background:i<step?'#0ABDC0':'#d0e8e8',maxWidth:50}}/>}
        </span>
      ))}
    </div>
  );
  const Card = ({children}) => <div style={{background:'white',borderRadius:16,padding:26,boxShadow:'0 4px 24px rgba(10,189,192,0.08)',marginBottom:20,border:'1px solid #d0e8e8'}}>{children}</div>;
  const inp = {width:'100%',fontFamily:"'DM Sans',sans-serif",fontSize:'0.88rem',border:'1.5px solid #d0e8e8',borderRadius:10,padding:'11px 14px',background:'white',color:'#1a2e2e',outline:'none',resize:'vertical',boxSizing:'border-box'};
  const lbl = {display:'block',fontSize:'0.82rem',fontWeight:600,color:'#1a2e2e',marginBottom:6};
  const btnP = {padding:'12px 24px',borderRadius:10,fontFamily:"'DM Sans',sans-serif",fontSize:'0.88rem',fontWeight:600,cursor:'pointer',border:'none',background:'linear-gradient(135deg,#0ABDC0,#078b8e)',color:'white',boxShadow:'0 4px 14px rgba(10,189,192,0.3)',display:'inline-flex',alignItems:'center',gap:7};
  const btnS = {padding:'12px 24px',borderRadius:10,fontFamily:"'DM Sans',sans-serif",fontSize:'0.88rem',fontWeight:600,cursor:'pointer',background:'white',color:'#5a7272',border:'1.5px solid #d0e8e8'};

  const Header = () => (
    <header style={{background:'linear-gradient(135deg,#0ABDC0,#078b8e)',boxShadow:'0 2px 20px rgba(10,189,192,0.2)'}}>
      <div style={{maxWidth:1000,margin:'0 auto',padding:'14px 24px',display:'flex',alignItems:'center',gap:14}}>
        <img src={`data:image/png;base64,${LOGO}`} alt="Nutri Secrets" style={{height:48,width:'auto',filter:'brightness(0) invert(1)'}}/>
        <div>
          <p style={{color:'white',fontSize:'0.85rem',fontWeight:600,margin:0}}>ANA App · Nutri Secrets</p>
          <p style={{color:'rgba(255,255,255,0.75)',fontSize:'0.72rem',margin:0}}>Nutrição terapêutica personalizada com base científica</p>
        </div>
      </div>
    </header>
  );

  const Chatbot = () => (
    <>
      <button onClick={()=>setChatOpen(o=>!o)}
        style={{position:'fixed',bottom:24,right:24,width:58,height:58,borderRadius:'50%',background:'linear-gradient(135deg,#0ABDC0,#078b8e)',border:'none',cursor:'pointer',boxShadow:'0 4px 20px rgba(10,189,192,0.5)',display:'flex',alignItems:'center',justifyContent:'center',zIndex:1000,transition:'all 0.3s',fontSize:'1.5rem'}}>
        {chatOpen?'✕':'💬'}
      </button>
      {chatOpen && (
        <div style={{position:'fixed',bottom:96,right:24,width:360,maxWidth:'calc(100vw - 32px)',background:'white',borderRadius:20,boxShadow:'0 8px 40px rgba(0,0,0,0.18)',zIndex:999,display:'flex',flexDirection:'column',overflow:'hidden',maxHeight:'72vh'}}>
          <div style={{background:'linear-gradient(135deg,#0ABDC0,#078b8e)',padding:'14px 18px',display:'flex',alignItems:'center',gap:12}}>
            <div style={{width:38,height:38,borderRadius:'50%',background:'rgba(255,255,255,0.2)',display:'flex',alignItems:'center',justifyContent:'center',fontSize:'1.2rem',flexShrink:0}}>🌿</div>
            <div>
              <p style={{color:'white',fontWeight:600,fontSize:'0.9rem',margin:0}}>ANA — Assistente Nutricional</p>
              <p style={{color:'rgba(255,255,255,0.75)',fontSize:'0.7rem',margin:0}}>Nutrição terapêutica · Nutri Secrets</p>
            </div>
          </div>
          <div style={{flex:1,overflowY:'auto',padding:'14px',display:'flex',flexDirection:'column',gap:10}}>
            {chatMsgs.map((m,i)=>(
              <div key={i} style={{display:'flex',justifyContent:m.role==='user'?'flex-end':'flex-start'}}>
                <div style={{maxWidth:'86%',padding:'10px 13px',borderRadius:m.role==='user'?'16px 16px 4px 16px':'16px 16px 16px 4px',background:m.role==='user'?'linear-gradient(135deg,#0ABDC0,#078b8e)':'#f4fafa',color:m.role==='user'?'white':'#1a2e2e',fontSize:'0.83rem',lineHeight:1.55,border:m.role==='user'?'none':'1px solid #e0f0f0',whiteSpace:'pre-wrap'}}>
                  {m.text}
                </div>
              </div>
            ))}
            {chatLoading && (
              <div style={{display:'flex',justifyContent:'flex-start'}}>
                <div style={{padding:'10px 14px',borderRadius:'16px 16px 16px 4px',background:'#f4fafa',border:'1px solid #e0f0f0',fontSize:'0.83rem',color:'#5a7272'}}>
                  ✦ Pensando...
                </div>
              </div>
            )}
            <div ref={chatEndRef}/>
          </div>
          {chatMsgs.length<=1 && (
            <div style={{padding:'4px 12px 8px',display:'flex',flexWrap:'wrap',gap:6}}>
              {['💧 Hidratação diária','🥗 Dieta para emagrecer','😴 Alimentos para dormir','⚡ Aumentar energia','🌿 Receitas terapêuticas','🔬 Interpretar exame'].map(s=>(
                <button key={s} onClick={()=>setChatInput(s.slice(2))} style={{padding:'5px 9px',borderRadius:20,border:'1px solid #d0e8e8',background:'white',fontSize:'0.71rem',color:'#5a7272',cursor:'pointer'}}>{s}</button>
              ))}
            </div>
          )}
          <div style={{padding:'10px 14px',borderTop:'1px solid #e0f0f0',display:'flex',gap:8,background:'white'}}>
            <input value={chatInput} onChange={e=>setChatInput(e.target.value)} onKeyDown={e=>e.key==='Enter'&&!e.shiftKey&&sendChat()}
              placeholder="Pergunte sobre nutrição e receitas..."
              style={{flex:1,padding:'9px 13px',borderRadius:10,border:'1.5px solid #d0e8e8',fontFamily:"'DM Sans',sans-serif",fontSize:'0.83rem',outline:'none',color:'#1a2e2e'}}/>
            <button onClick={sendChat} disabled={chatLoading||!chatInput.trim()}
              style={{width:38,height:38,borderRadius:10,background:chatInput.trim()?'linear-gradient(135deg,#0ABDC0,#078b8e)':'#e5e5e5',border:'none',cursor:chatInput.trim()?'pointer':'default',display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0,fontSize:'1rem',color:'white'}}>➤</button>
          </div>
        </div>
      )}
    </>
  );

  // WELCOME SCREEN
  if (screen==='welcome') return (
    <>
      <Head>
        <title>ANA App · Nutri Secrets</title>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/>
        <style>{`*{box-sizing:border-box;margin:0;padding:0}body{font-family:'DM Sans',sans-serif;background:#F4FAFA;color:#1a2e2e}@keyframes fadeUp{from{opacity:0;transform:translateY(24px)}to{opacity:1;transform:none}}@keyframes pulse{0%,100%{opacity:1}50%{opacity:0.5}}`}</style>
      </Head>
      <div style={{minHeight:'100vh',background:'linear-gradient(160deg,#0a2e2e 0%,#0d3535 45%,#0a2922 100%)',display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'40px 24px',position:'relative',overflow:'hidden'}}>
        <div style={{position:'absolute',top:-120,right:-120,width:450,height:450,borderRadius:'50%',background:'radial-gradient(circle,rgba(10,189,192,0.13) 0%,transparent 70%)',pointerEvents:'none'}}/>
        <div style={{position:'absolute',bottom:-80,left:-80,width:320,height:320,borderRadius:'50%',background:'radial-gradient(circle,rgba(249,115,22,0.08) 0%,transparent 70%)',pointerEvents:'none'}}/>
        <div style={{maxWidth:480,width:'100%',textAlign:'center',animation:'fadeUp 0.8s ease'}}>
          <img src={`data:image/png;base64,${LOGO}`} alt="Nutri Secrets" style={{height:72,width:'auto',filter:'brightness(0) invert(1)',marginBottom:28}}/>
          <div style={{display:'inline-flex',alignItems:'center',gap:7,background:'rgba(10,189,192,0.15)',border:'1px solid rgba(10,189,192,0.3)',borderRadius:100,padding:'6px 16px',marginBottom:28}}>
            <span style={{width:7,height:7,borderRadius:'50%',background:'#0ABDC0',display:'inline-block',animation:'pulse 2s infinite'}}/>
            <span style={{color:'#0ABDC0',fontSize:'0.74rem',fontWeight:600,letterSpacing:1,textTransform:'uppercase'}}>ANA App · Em parceria com Nutri Secrets</span>
          </div>
          <h1 style={{fontFamily:"'Playfair Display',serif",fontSize:'clamp(1.9rem,5vw,2.7rem)',fontWeight:700,color:'white',lineHeight:1.2,marginBottom:18}}>
            Seja bem-vindo ao<br/><span style={{color:'#0ABDC0'}}>ANA App</span>
          </h1>
          <p style={{color:'rgba(255,255,255,0.72)',fontSize:'0.97rem',lineHeight:1.7,marginBottom:10,maxWidth:380,margin:'0 auto 10px'}}>
            Aqui você tem orientações nutricionais baseadas em evidência com a metodologia focada em
          </p>
          <p style={{color:'rgba(255,255,255,0.5)',fontSize:'0.84rem',lineHeight:1.7,marginBottom:36,maxWidth:380,margin:'0 auto 36px'}}>
            <span style={{color:'#0ABDC0',fontWeight:600}}>sinergia nutricional</span> e <span style={{color:'#0ABDC0',fontWeight:600}}>nutrição terapêutica</span> — conectando alimentos, sintomas e saúde de forma integrada e personalizada.
          </p>
          <div style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:10,marginBottom:36}}>
            {[['🧬','Baseado em evidências científicas'],['🌿','278+ receitas terapêuticas'],['💬','Chat com IA especializada']].map(([icon,text])=>(
              <div key={text} style={{background:'rgba(255,255,255,0.06)',borderRadius:12,padding:'14px 8px',border:'1px solid rgba(255,255,255,0.09)'}}>
                <div style={{fontSize:'1.5rem',marginBottom:6}}>{icon}</div>
                <p style={{color:'rgba(255,255,255,0.6)',fontSize:'0.7rem',lineHeight:1.4}}>{text}</p>
              </div>
            ))}
          </div>
          <button onClick={()=>setScreen('app')} style={{padding:'16px 48px',borderRadius:14,fontFamily:"'DM Sans',sans-serif",fontSize:'1.05rem',fontWeight:700,cursor:'pointer',border:'none',background:'linear-gradient(135deg,#0ABDC0,#078b8e)',color:'white',boxShadow:'0 6px 30px rgba(10,189,192,0.4)',width:'100%',maxWidth:300}}>
            Continuar →
          </button>
          <p style={{color:'rgba(255,255,255,0.3)',fontSize:'0.72rem',marginTop:14}}>Gere seu cardápio terapêutico personalizado gratuitamente</p>
        </div>
      </div>
      <Chatbot/>
    </>
  );

  // MAIN APP
  return (
    <>
      <Head>
        <title>ANA App · Nutri Secrets</title>
        <meta name="viewport" content="width=device-width,initial-scale=1"/>
        <link href="https://fonts.googleapis.com/css2?family=Playfair+Display:wght@400;600;700&family=DM+Sans:wght@300;400;500;600&display=swap" rel="stylesheet"/>
        <style>{`
          *{box-sizing:border-box;margin:0;padding:0}
          body{font-family:'DM Sans',sans-serif;background:#F4FAFA;color:#1a2e2e;min-height:100vh;font-size:14px}
          input,textarea{-webkit-user-select:text!important;user-select:text!important;touch-action:manipulation}
          .res h2{font-family:'Playfair Display',serif;font-size:1.15rem;color:#078b8e;margin:24px 0 8px;padding-bottom:6px;border-bottom:2px solid #E0F7F8;page-break-after:avoid}
          .res h2:first-child{margin-top:0}
          .res h3{font-size:0.95rem;font-weight:700;color:#d95f0a;margin:18px 0 5px;page-break-after:avoid}
          .res ul{padding-left:20px;margin:6px 0 12px}
          .res li{margin-bottom:5px;line-height:1.6}
          .res strong{color:#078b8e}
          .res p{margin-bottom:8px;line-height:1.75}
          @keyframes sp{to{transform:rotate(360deg)}}
          @keyframes fi{from{opacity:0;transform:translateY(8px)}to{opacity:1;transform:none}}
          @media print{nav,header,.tabs,.acts,.no-print{display:none!important}.res{padding:0!important;box-shadow:none!important;border:none!important}body{font-size:11px}}
          @media(max-width:600px){.r2,.r3{grid-template-columns:1fr!important}}
        `}</style>
      </Head>
      <Header/>
      <div className="tabs" style={{background:'white',borderBottom:'2px solid #d0e8e8',position:'sticky',top:0,zIndex:100,boxShadow:'0 2px 12px rgba(0,0,0,0.05)'}}>
        <div style={{maxWidth:1000,margin:'0 auto',display:'flex',padding:'0 24px',overflowX:'auto'}}>
          {[['1','Dados Pessoais'],['2','Sintomas & Exame'],['3','Preferências'],['✨','Meu Cardápio']].map(([n,l],i)=>(
            <button key={i} onClick={()=>setTab(i)} style={{padding:'14px 18px',border:'none',background:'transparent',fontFamily:"'DM Sans',sans-serif",fontSize:'0.82rem',fontWeight:tab===i?600:500,color:tab===i?'#0ABDC0':'#5a7272',cursor:'pointer',borderBottom:`3px solid ${tab===i?'#0ABDC0':'transparent'}`,marginBottom:-2,transition:'all 0.2s',whiteSpace:'nowrap',display:'flex',alignItems:'center',gap:6}}>
              <span style={{width:20,height:20,borderRadius:'50%',background:tab===i?'#0ABDC0':'#E0F7F8',color:tab===i?'white':'#078b8e',fontSize:'0.7rem',fontWeight:700,display:'flex',alignItems:'center',justifyContent:'center',flexShrink:0}}>{n}</span>{l}
            </button>
          ))}
        </div>
      </div>
      <main style={{maxWidth:1000,margin:'0 auto',padding:'28px 24px 100px',animation:'fi 0.3s ease'}}>

        {tab===0&&<div>
          {prog(0)}
          <Card>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:4}}>👤 Seus Dados Pessoais</p>
            <p style={{color:'#5a7272',fontSize:'0.8rem',marginBottom:18,lineHeight:1.5}}>Usados para calcular suas necessidades calóricas e criar um plano individualizado.</p>
            <div className="r2" style={{display:'grid',gridTemplateColumns:'1fr 1fr',gap:16,marginBottom:18}}>
              <div><label style={lbl}>Nome</label><input style={inp} value={nome} onChange={e=>setNome(e.target.value)} placeholder="Seu nome completo" autoComplete="off"/></div>
              <div><label style={lbl}>Idade</label><input style={inp} type="number" inputMode="numeric" value={idade} onChange={e=>setIdade(e.target.value)} placeholder="Ex: 35"/></div>
            </div>
            <div className="r3" style={{display:'grid',gridTemplateColumns:'1fr 1fr 1fr',gap:16,marginBottom:18}}>
              <div><label style={lbl}>Peso (kg)</label><input style={inp} type="number" inputMode="decimal" value={peso} onChange={e=>setPeso(e.target.value)} placeholder="Ex: 75"/></div>
              <div><label style={lbl}>Altura (cm)</label><input style={inp} type="number" inputMode="numeric" value={altura} onChange={e=>setAltura(e.target.value)} placeholder="Ex: 170"/></div>
              <div><label style={lbl}>Meta de perda (kg)</label><input style={inp} type="number" inputMode="decimal" value={meta} onChange={e=>setMeta(e.target.value)} placeholder="Ex: 8 ou 0"/></div>
            </div>
            <div style={{marginBottom:18}}>
              <label style={lbl}>Sexo biológico</label>
              <div style={{display:'flex',flexWrap:'wrap'}}>{['♀️ Feminino','♂️ Masculino'].map(v=><SChip key={v} v={v} cur={sexo} set={setSexo}/>)}</div>
            </div>
            <div>
              <label style={lbl}>Nível de atividade física</label>
              <div style={{display:'flex',flexWrap:'wrap'}}>{['😴 Sedentário','🚶 Leve (1-2x/sem)','🏃 Moderado (3-4x/sem)','💪 Intenso (5+/sem)'].map(v=><SChip key={v} v={v} cur={atv} set={setAtv}/>)}</div>
            </div>
          </Card>
          <div style={{display:'flex',justifyContent:'flex-end',marginTop:26}}><button onClick={()=>setTab(1)} style={btnP}>Próximo: Sintomas &amp; Exame →</button></div>
        </div>}

        {tab===1&&<div>
          {prog(1)}
          <Card>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:4}}>📋 Exame de Sangue (PDF)</p>
            <p style={{color:'#5a7272',fontSize:'0.8rem',marginBottom:18,lineHeight:1.5}}>Opcional. Analisaremos glicemia, colesterol, enzimas hepáticas, vitaminas e mais.</p>
            <div onDragOver={e=>{e.preventDefault();setDrag(true)}} onDragLeave={()=>setDrag(false)} onDrop={e=>{e.preventDefault();setDrag(false);procPdf(e.dataTransfer.files[0])}} style={{border:`2.5px dashed ${drag?'#0ABDC0':'#d0e8e8'}`,borderRadius:16,padding:'32px 24px',textAlign:'center',cursor:'pointer',background:drag?'#c8f0f1':'#E0F7F8',position:'relative',transition:'all 0.25s'}}>
              <input type="file" accept=".pdf" onChange={e=>procPdf(e.target.files[0])} style={{position:'absolute',inset:0,opacity:0,cursor:'pointer',width:'100%',height:'100%'}}/>
              <div style={{fontSize:'2rem'}}>📋</div>
              <p style={{fontSize:'0.95rem',fontWeight:600,color:'#078b8e',margin:'8px 0 4px'}}>Clique ou arraste seu exame aqui</p>
              <p style={{fontSize:'0.78rem',color:'#5a7272'}}>Formato: PDF · Máx 20MB</p>
            </div>
            {pdf&&<div style={{display:'flex',alignItems:'center',gap:10,padding:'12px 16px',background:'#E0F7F8',borderRadius:10,border:'1.5px solid #0ABDC0',marginTop:14}}>
              <span style={{fontSize:'1.5rem'}}>📄</span>
              <div style={{flex:1}}><div style={{fontWeight:600,fontSize:'0.84rem',color:'#078b8e'}}>{pdfName}</div></div>
              <button onClick={()=>{setPdf(null);setPdfName('');}} style={{background:'none',border:'none',cursor:'pointer',color:'#5a7272',fontSize:'1.1rem'}}>✕</button>
            </div>}
          </Card>
          <Card>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:4}}>🩺 Sintomas e Objetivos</p>
            <p style={{color:'#5a7272',fontSize:'0.8rem',marginBottom:18,lineHeight:1.5}}>Descreva o que sente. Quanto mais detalhes, mais preciso o cardápio.</p>
            <div style={{marginBottom:18}}>
              <label style={lbl}>Descreva seus sintomas e objetivos *</label>
              <textarea style={{...inp,minHeight:100}} value={sintTxt} onChange={e=>setSintTxt(e.target.value)} placeholder="Ex: Tenho ansiedade, insônia, intestino irregular e quero emagrecer. Sinto cansaço constante..."/>
            </div>
            <div>
              <label style={lbl}>Selecione seus sintomas principais</label>
              <div style={{display:'flex',flexWrap:'wrap'}}>{SINTS.map(v=><Chip key={v} v={v} sel={sintSel} onTog={v=>tog(sintSel,setSintSel,v)}/>)}</div>
            </div>
          </Card>
          <div style={{display:'flex',justifyContent:'space-between',marginTop:26}}>
            <button onClick={()=>setTab(0)} style={btnS}>← Voltar</button>
            <button onClick={()=>setTab(2)} style={btnP}>Próximo: Preferências →</button>
          </div>
        </div>}

        {tab===2&&<div>
          {prog(2)}
          <Card>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:4}}>🌱 Restrições Alimentares</p>
            <p style={{color:'#5a7272',fontSize:'0.8rem',marginBottom:18,lineHeight:1.5}}>Selecione todas que se aplicam. Seu cardápio será 100% adaptado.</p>
            <div style={{display:'flex',flexWrap:'wrap'}}>{DIETS.map(v=><Chip key={v} v={v} sel={dietSel} onTog={v=>tog(dietSel,setDietSel,v)}/>)}</div>
          </Card>
          <Card>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:4}}>🍽️ Refeições do Dia</p>
            <p style={{color:'#5a7272',fontSize:'0.8rem',marginBottom:18,lineHeight:1.5}}>Selecione as refeições que deseja incluir no cardápio.</p>
            <div style={{display:'flex',flexWrap:'wrap'}}>{MEALS.map(v=><Chip key={v} v={v} sel={mealSel} onTog={v=>tog(mealSel,setMealSel,v)} meal/>)}</div>
          </Card>
          <Card>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:4}}>✏️ Observações Adicionais</p>
            <p style={{color:'#5a7272',fontSize:'0.8rem',marginBottom:18,lineHeight:1.5}}>Alimentos que não gosta, alergias, horários, contexto de vida...</p>
            <textarea style={{...inp,minHeight:90}} value={extras} onChange={e=>setExtras(e.target.value)} placeholder="Ex: Não gosto de couve. Almoço fora de casa. Alergia a frutos do mar..."/>
          </Card>
          <div style={{textAlign:'center',padding:'32px 16px'}}>
            <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.5rem',fontWeight:600,marginBottom:8}}>Tudo pronto? ✨</p>
            <p style={{color:'#5a7272',marginBottom:24,fontSize:'0.87rem'}}>Gere agora seu cardápio terapêutico com receitas reais da Nutri Secrets.</p>
            <button onClick={generate} style={{padding:'15px 36px',borderRadius:12,fontFamily:"'DM Sans',sans-serif",fontSize:'0.98rem',fontWeight:600,cursor:'pointer',border:'none',background:'linear-gradient(135deg,#F97316,#d95f0a)',color:'white',boxShadow:'0 4px 18px rgba(249,115,22,0.35)',display:'inline-flex',alignItems:'center',gap:8}}>
              🌿 Gerar Meu Cardápio Terapêutico
            </button>
            {err&&<div style={{background:'#fff5f5',border:'1.5px solid #fca5a5',borderRadius:10,padding:'14px 18px',color:'#b91c1c',fontSize:'0.84rem',marginTop:14}}>⚠️ {err}</div>}
          </div>
          <div><button onClick={()=>setTab(1)} style={btnS}>← Voltar</button></div>
        </div>}

        {tab===3&&<div>
          {loading?(
            <div style={{display:'flex',flexDirection:'column',alignItems:'center',justifyContent:'center',padding:'60px 20px',textAlign:'center'}}>
              <div style={{width:48,height:48,border:'4px solid #E0F7F8',borderTopColor:'#0ABDC0',borderRadius:'50%',animation:'sp 0.9s linear infinite',marginBottom:20}}/>
              <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.15rem',fontWeight:600,marginBottom:8}}>Criando seu cardápio terapêutico…</p>
              <p style={{color:'#5a7272',fontSize:'0.84rem',lineHeight:1.6}}>Selecionando receitas terapêuticas personalizadas<br/>e correlacionando com seus sintomas e exames.</p>
            </div>
          ):result?(
            <div style={{animation:'fi 0.4s ease'}}>
              <div className="no-print" style={{background:'linear-gradient(135deg,#0ABDC0,#078b8e)',borderRadius:16,padding:'22px 26px',color:'white',marginBottom:18,display:'flex',alignItems:'center',gap:16}}>
                <div style={{fontSize:'2.2rem'}}>🌿</div>
                <div>
                  <p style={{fontFamily:"'Playfair Display',serif",fontSize:'1.3rem',fontWeight:600,marginBottom:3}}>Seu Cardápio Terapêutico Personalizado</p>
                  <p style={{opacity:0.82,fontSize:'0.8rem'}}>{sub}</p>
                </div>
              </div>
              <div className="acts no-print" style={{display:'flex',gap:10,marginBottom:18,flexWrap:'wrap'}}>
                <button onClick={()=>window.print()} style={{background:'white',border:'1.5px solid #d0e8e8',color:'#5a7272',fontSize:'0.8rem',padding:'9px 16px',borderRadius:10,cursor:'pointer'}}>🖨️ Imprimir / Salvar PDF</button>
                <button onClick={()=>{setResult('');setTab(0);}} style={{background:'white',border:'1.5px solid #d0e8e8',color:'#5a7272',fontSize:'0.8rem',padding:'9px 16px',borderRadius:10,cursor:'pointer'}}>🔄 Novo cardápio</button>
              </div>
              <div className="res" style={{background:'white',borderRadius:16,padding:28,boxShadow:'0 4px 24px rgba(10,189,192,0.08)',border:'1px solid #d0e8e8',fontSize:'0.9rem',lineHeight:1.75,color:'#1a2e2e'}} dangerouslySetInnerHTML={{__html:fmt(result)}}/>
              <div style={{background:'white',borderRadius:16,overflow:'hidden',marginTop:20,border:'1px solid #d0e8e8'}}>
                <div style={{background:'linear-gradient(135deg,#0ABDC0,#078b8e)',padding:'18px 22px',display:'flex',alignItems:'center',gap:14}}>
                  <div style={{fontSize:'1.8rem'}}>🥗</div>
                  <div>
                    <p style={{color:'white',fontFamily:"'Playfair Display',serif",fontSize:'1rem',fontWeight:600,marginBottom:3}}>Quer acompanhamento personalizado?</p>
                    <p style={{color:'rgba(255,255,255,0.85)',fontSize:'0.8rem',lineHeight:1.5}}>Conheça nossos nutris especializados em nutrição de precisão integrativa — detectives da sua saúde.</p>
                  </div>
                </div>
                <div style={{padding:'14px 22px',background:'white',display:'flex',alignItems:'center',justifyContent:'space-between',flexWrap:'wrap',gap:10}}>
                  <p style={{color:'#5a7272',fontSize:'0.8rem'}}>Acompanhamento com nutricionistas especializados</p>
                  <a href="https://dralinequissak.com/" target="_blank" rel="noopener noreferrer" style={{padding:'10px 20px',background:'linear-gradient(135deg,#0ABDC0,#078b8e)',color:'white',borderRadius:10,fontSize:'0.82rem',fontWeight:600,textDecoration:'none',whiteSpace:'nowrap'}}>
                    Conheça nossos nutris →
                  </a>
                </div>
              </div>
              <div style={{marginTop:16,borderRadius:16,overflow:'hidden',background:'linear-gradient(135deg,#1a0a2e 0%,#0d1a2e 60%,#0a2e1a 100%)',position:'relative'}}>
                <div style={{position:'absolute',inset:0,backgroundImage:'radial-gradient(ellipse at 25% 50%, rgba(10,189,192,0.15) 0%, transparent 60%)',pointerEvents:'none'}}/>
                <div style={{padding:'24px 22px',display:'flex',alignItems:'center',gap:18,position:'relative'}}>
                  <div style={{fontSize:'2.2rem',flexShrink:0}}>🧬</div>
                  <div style={{flex:1}}>
                    <p style={{color:'rgba(255,255,255,0.55)',fontSize:'0.7rem',fontWeight:600,letterSpacing:2,textTransform:'uppercase',marginBottom:5}}>Nutrigenética</p>
                    <p style={{color:'white',fontFamily:"'Playfair Display',serif",fontSize:'1.05rem',fontWeight:600,lineHeight:1.4,marginBottom:7}}>Quer mais precisão no diagnóstico?</p>
                    <p style={{color:'rgba(255,255,255,0.7)',fontSize:'0.8rem',lineHeight:1.6,marginBottom:14}}>Faça seu teste genético e desvende seu metabolismo para cuidar dos seus sintomas atuais e prevenir doenças com o poder da nutrigenética.</p>
                    <a href="https://funil.scannerdasaude.digital/scanner" target="_blank" rel="noopener noreferrer" style={{display:'inline-flex',alignItems:'center',gap:7,padding:'11px 20px',background:'linear-gradient(135deg,#F97316,#d95f0a)',color:'white',borderRadius:10,fontSize:'0.82rem',fontWeight:600,textDecoration:'none',boxShadow:'0 4px 18px rgba(249,115,22,0.4)'}}>
                      🧬 Desvende seu metabolismo →
                    </a>
                  </div>
                </div>
              </div>
              <div style={{background:'#FFF0E6',borderLeft:'4px solid #F97316',borderRadius:'0 10px 10px 0',padding:'11px 15px',fontSize:'0.76rem',color:'#d95f0a',marginTop:14,lineHeight:1.5}}>⚠️ <strong>Aviso:</strong> Este cardápio é uma sugestão educativa baseada em evidências. Não substitui consulta com médico ou nutricionista.</div>
            </div>
          ):null}
        </div>}
      </main>
      <Chatbot/>
    </>
  );
}
